"use client";

import { usePathname } from "next/navigation";
import { JsonLd } from "@/components/seo/JsonLd";
import type { Locale } from "@/i18n/routing";
import { SITE_URL } from "@/lib/constants";
import { breadcrumbJsonLd } from "@/lib/jsonld";

const homeLabels: Record<Locale, string> = {
  ar: "الرئيسية",
  fr: "Accueil",
  en: "Home",
  es: "Inicio",
};

const routeLabels: Record<Locale, Record<string, string>> = {
  ar: {
    "/solutions": "الحلول",
    "/features": "المزايا",
    "/institutions/schools": "المدارس",
    "/institutions/institutes": "المعاهد",
    "/institutions/tutoring-centers": "مراكز الدعم",
    "/institutions/language-centers": "مراكز اللغات",
    "/roles/administration": "الإدارة",
    "/roles/teachers": "الأساتذة",
    "/roles/parents": "أولياء الأمور",
    "/roles/students": "التلاميذ",
    "/timetable": "استعمال الزمن",
    "/security": "الأمان والصلاحيات",
    "/about": "عن رقيم",
    "/demo": "طلب عرض توضيحي",
    "/contact": "تواصل معنا",
    "/faq": "الأسئلة الشائعة",
    "/privacy": "سياسة الخصوصية",
    "/terms": "شروط الاستخدام",
    "/support": "الدعم",
    "/data-deletion": "حذف البيانات",
    "/compliance": "الامتثال",
    "/privacy-center": "مركز الخصوصية",
    "/trust-center": "مركز الثقة",
    "/legal-notice": "الإشعار القانوني",
    "/cookies": "ملفات تعريف الارتباط",
    "/accessibility": "إمكانية الوصول",
    "/child-parent-data-notice": "إشعار بيانات الأطفال وأولياء الأمور",
    "/data-processing-agreement": "اتفاقية معالجة البيانات",
    "/subprocessors": "المعالجون الفرعيون",
    "/data-retention": "الاحتفاظ بالبيانات",
    "/backup-recovery": "النسخ الاحتياطي والاسترجاع",
    "/service-status": "حالة الخدمة",
    "/service-level-agreement": "اتفاقية مستوى الخدمة",
    "/business-continuity": "استمرارية الأعمال",
    "/disaster-recovery": "التعافي من الكوارث",
    "/incident-response": "الاستجابة للحوادث",
    "/vulnerability-disclosure": "الإفصاح عن الثغرات",
    "/security-contact": "الاتصال الأمني",
    "/support-policy": "سياسة الدعم",
    "/maintenance-policy": "سياسة الصيانة",
    "/security-whitepaper": "الورقة البيضاء للأمان",
    "/responsible-ai": "الذكاء الاصطناعي المسؤول",
  },
  fr: {
    "/solutions": "Solutions",
    "/features": "Fonctionnalités",
    "/institutions/schools": "Écoles",
    "/institutions/institutes": "Instituts",
    "/institutions/tutoring-centers": "Centres de soutien",
    "/institutions/language-centers": "Centres de langues",
    "/roles/administration": "Administration",
    "/roles/teachers": "Enseignants",
    "/roles/parents": "Parents",
    "/roles/students": "Élèves",
    "/timetable": "Emploi du temps",
    "/security": "Sécurité et autorisations",
    "/about": "À propos de Raqeem",
    "/demo": "Demander une démonstration",
    "/contact": "Nous contacter",
    "/faq": "Questions fréquentes",
    "/privacy": "Politique de confidentialité",
    "/terms": "Conditions d’utilisation",
    "/support": "Support",
    "/data-deletion": "Suppression des données",
    "/compliance": "Conformité",
    "/privacy-center": "Centre de confidentialité",
    "/trust-center": "Centre de confiance",
    "/legal-notice": "Mentions légales",
    "/cookies": "Cookies",
    "/accessibility": "Accessibilité",
    "/child-parent-data-notice": "Notice sur les données des enfants et parents",
    "/data-processing-agreement": "Accord de traitement des données",
    "/subprocessors": "Sous-traitants ultérieurs",
    "/data-retention": "Conservation des données",
    "/backup-recovery": "Sauvegarde et restauration",
    "/service-status": "État du service",
    "/service-level-agreement": "Accord de niveau de service",
    "/business-continuity": "Continuité d’activité",
    "/disaster-recovery": "Reprise après sinistre",
    "/incident-response": "Réponse aux incidents",
    "/vulnerability-disclosure": "Divulgation des vulnérabilités",
    "/security-contact": "Contact sécurité",
    "/support-policy": "Politique de support",
    "/maintenance-policy": "Politique de maintenance",
    "/security-whitepaper": "Livre blanc de sécurité",
    "/responsible-ai": "IA responsable",
  },
  en: {
    "/solutions": "Solutions",
    "/features": "Features",
    "/institutions/schools": "Schools",
    "/institutions/institutes": "Institutes",
    "/institutions/tutoring-centers": "Tutoring centers",
    "/institutions/language-centers": "Language centers",
    "/roles/administration": "Administration",
    "/roles/teachers": "Teachers",
    "/roles/parents": "Parents",
    "/roles/students": "Students",
    "/timetable": "Timetable",
    "/security": "Security and permissions",
    "/about": "About Raqeem",
    "/demo": "Request a demo",
    "/contact": "Contact us",
    "/faq": "Frequently asked questions",
    "/privacy": "Privacy policy",
    "/terms": "Terms of use",
    "/support": "Support",
    "/data-deletion": "Data deletion",
    "/compliance": "Compliance",
    "/privacy-center": "Privacy center",
    "/trust-center": "Trust center",
    "/legal-notice": "Legal notice",
    "/cookies": "Cookies",
    "/accessibility": "Accessibility",
    "/child-parent-data-notice": "Child and parent data notice",
    "/data-processing-agreement": "Data processing agreement",
    "/subprocessors": "Subprocessors",
    "/data-retention": "Data retention",
    "/backup-recovery": "Backup and recovery",
    "/service-status": "Service status",
    "/service-level-agreement": "Service level agreement",
    "/business-continuity": "Business continuity",
    "/disaster-recovery": "Disaster recovery",
    "/incident-response": "Incident response",
    "/vulnerability-disclosure": "Vulnerability disclosure",
    "/security-contact": "Security contact",
    "/support-policy": "Support policy",
    "/maintenance-policy": "Maintenance policy",
    "/security-whitepaper": "Security whitepaper",
    "/responsible-ai": "Responsible AI",
  },
  es: {
    "/solutions": "Soluciones",
    "/features": "Funciones",
    "/institutions/schools": "Colegios",
    "/institutions/institutes": "Institutos",
    "/institutions/tutoring-centers": "Centros de apoyo",
    "/institutions/language-centers": "Centros de idiomas",
    "/roles/administration": "Administración",
    "/roles/teachers": "Docentes",
    "/roles/parents": "Familias",
    "/roles/students": "Alumnos",
    "/timetable": "Horario",
    "/security": "Seguridad y permisos",
    "/about": "Acerca de Raqeem",
    "/demo": "Solicitar una demostración",
    "/contact": "Contacto",
    "/faq": "Preguntas frecuentes",
    "/privacy": "Política de privacidad",
    "/terms": "Condiciones de uso",
    "/support": "Soporte",
    "/data-deletion": "Eliminación de datos",
    "/compliance": "Cumplimiento",
    "/privacy-center": "Centro de privacidad",
    "/trust-center": "Centro de confianza",
    "/legal-notice": "Aviso legal",
    "/cookies": "Cookies",
    "/accessibility": "Accesibilidad",
    "/child-parent-data-notice": "Aviso de datos de menores y familias",
    "/data-processing-agreement": "Acuerdo de tratamiento de datos",
    "/subprocessors": "Subencargados",
    "/data-retention": "Conservación de datos",
    "/backup-recovery": "Copias de seguridad y recuperación",
    "/service-status": "Estado del servicio",
    "/service-level-agreement": "Acuerdo de nivel de servicio",
    "/business-continuity": "Continuidad del negocio",
    "/disaster-recovery": "Recuperación ante desastres",
    "/incident-response": "Respuesta ante incidentes",
    "/vulnerability-disclosure": "Divulgación de vulnerabilidades",
    "/security-contact": "Contacto de seguridad",
    "/support-policy": "Política de soporte",
    "/maintenance-policy": "Política de mantenimiento",
    "/security-whitepaper": "Libro blanco de seguridad",
    "/responsible-ai": "IA responsable",
  },
};

export function RouteBreadcrumbJsonLd({ locale }: { locale: Locale }) {
  const pathname = usePathname();
  const localeRoot = `/${locale}`;
  const path = pathname.startsWith(localeRoot) ? pathname.slice(localeRoot.length) : "";
  const label = routeLabels[locale][path];

  if (!path || !label) {
    return null;
  }

  return (
    <JsonLd
      data={
        breadcrumbJsonLd([
          { name: homeLabels[locale], url: `${SITE_URL}/${locale}` },
          { name: label, url: `${SITE_URL}/${locale}${path}` },
        ])
      }
    />
  );
}
