import type { Locale } from "@/i18n/routing";

export interface FaqItem {
  question: string;
  answer: string;
}

export const faqItemsByLocale: Record<Locale, FaqItem[]> = {
  ar: [
    { question: "ما هو رقيم؟", answer: "رقيم منصة تشغيل وإدارة للمدارس الخاصة في المغرب، تربط التسجيل والتمدرس والمالية والتعليم والحضور واستعمال الزمن والتواصل المدرسي ضمن صلاحيات واضحة." },
    { question: "ما أنواع المؤسسات التي يخدمها رقيم؟", answer: "يخدم المدارس الخاصة، ويمكن تكييف المسارات المنشورة للمؤسسات التعليمية التي تتوافق احتياجاتها مع نطاق المنتج المتاح." },
    { question: "على أي أجهزة يعمل رقيم؟", answer: "يعمل رقيم على Web وWindows وAndroid وiOS، مع واجهات تتكيف مع نوع المهمة والدور وحجم الشاشة." },
    { question: "هل يمكن إدارة المدرسة من الهاتف والحاسوب؟", answer: "نعم. يناسب الهاتف المتابعة السريعة والمهام القصيرة، بينما تكون الجداول والعمليات الإدارية الطويلة أوضح غالبًا على Web أو Windows." },
    { question: "كيف يتحول طلب التسجيل إلى ملف تلميذ؟", answer: "تراجع الإدارة الطلب وتتحقق من التكرار وتربط ولي الأمر، ثم تحول الطلب المقبول إلى ملف تلميذ وتمدرس في السنة والمستوى والقسم الصحيحين." },
    { question: "ماذا يحدث إذا كان ولي الأمر موجودًا مسبقًا؟", answer: "يُربط بالسجل الموجود بعد التحقق بدل إنشاء سجل مكرر، مع الحفاظ على العلاقة الصحيحة بالتلميذ." },
    { question: "كيف تُنظم واجبات التمدرس والتحصيلات؟", answer: "تحدد الخطة المالية المبالغ والاستحقاقات، وتُسجل التحصيلات الفعلية بصورة مستقلة مع طريقة الأداء والتخصيص والمتبقي والمتأخر." },
    { question: "هل يمكن إصدار إيصال لدفعة جزئية؟", answer: "نعم، عندما تُسجل الدفعة كتحصيل فعلي. يعكس الإيصال المبلغ المستلم فقط ويبقى المتبقي ظاهرًا." },
    { question: "كيف يسجل رقيم الحضور والغياب؟", answer: "تُربط الحالة بالتلميذ والتاريخ والحصة أو الفترة، مع التفريق بين الغياب والتأخر والمغادرة المبكرة وإضافة التبرير عند مراجعته." },
    { question: "هل كل غياب يرسل إشعارًا تلقائيًا؟", answer: "يعتمد ذلك على إعداد وسياسة المؤسسة. أي إشعار يجب أن يستند إلى حالة صحيحة ومعتمدة وأن يصل إلى ولي الأمر المرتبط فقط." },
    { question: "كيف يدير رقيم استعمال الزمن؟", answer: "يدعم إعداد الأيام والفترات والموارد وبناء المسودة ومراجعة تعارضات الأستاذ والقسم والقاعة قبل الاعتماد والنشر." },
    { question: "هل يولد رقيم استعمال الزمن آليًا بالكامل؟", answer: "لا ينبغي افتراض التوليد الآلي الكامل. القدرة المنشورة هي إدارة المسودة ومراجعة التعارضات والاعتماد والنشر حسب الوظائف المتاحة." },
    { question: "كيف يعمل التواصل المدرسي؟", answer: "هو سجل رسمي تابع للمؤسسة، يحدد من يعد المحتوى ومن يراجعه ويعتمده ومن يتلقاه." },
    { question: "هل يستطيع الأستاذ مراسلة ولي الأمر مباشرة؟", answer: "لا خارج المسار المحكوم. وصول المحتوى إلى ولي الأمر أو التلميذ يمر بالمراجعة والموافقة الإدارية المقررة." },
    { question: "كيف تُدار الأدوار والصلاحيات؟", answer: "تُحدد القدرة ونطاق البيانات لكل دور، مثل المشاهدة والإنشاء والتعديل والحذف والمراجعة والاعتماد، مع تشديد العمليات الحساسة." },
    { question: "هل إخفاء زر يكفي لمنع العملية؟", answer: "لا. يجب أن تُطبق الصلاحية على العملية والبيانات نفسها، وليس على شكل الواجهة فقط." },
    { question: "كيف يعزل رقيم بيانات المدارس؟", answer: "يعمل كل عميل داخل نطاق مؤسسته المصرح به، ولا تُعرض بيانات مدرسة لمدرسة أخرى ولا تُنقل أساليب عملها أو إعداداتها إليها." },
    { question: "هل يقارن رقيم المدارس أو يشارك تجاربها؟", answer: "لا. لا تُقارن المدارس ولا تُنقل ممارساتها أو بياناتها، حتى بصورة مجهولة أو مجمعة بقصد مشاركة الأساليب." },
    { question: "هل يدعم رقيم المجموعات المدرسية والفروع؟", answer: "نعم ضمن علاقة إدارية فعلية وصلاحيات مركزية محددة، مع بقاء كل فرع داخل نطاقه واستقلال بياناته." },
    { question: "كيف يحمي رقيم بيانات التلاميذ والأسر؟", answer: "عبر عزل المؤسسة وأقل صلاحية لازمة وتقييد الحقول والملفات الحساسة ومراجعة الحسابات واستعمال بيانات تجريبية في الاختبارات." },
    { question: "هل يمكن الانتقال من Excel إلى رقيم؟", answer: "نعم عبر جرد الملفات وتنظيف التكرار والصيغ وتجربة استيراد محدودة ومطابقة النتائج قبل الانتقال الكامل." },
    { question: "ما علاقة رقيم بمسار؟", answer: "رقيم يدير التشغيل اليومي للمدرسة، ويمكنه توليد ملفات مهيأة وقابلة للرفع على مسار وفق صيغة التصدير المدعومة، ثم يراجعها ويرفعها المستخدم المخول." },
    { question: "هل يستطيع رقيم توليد ملفات قابلة للرفع على مسار؟", answer: "نعم. يمكنه توليد ملفات مهيأة للرفع انطلاقًا من البيانات المتوفرة والمراجعة، مع ضرورة فحص الحقول والسجلات والصيغة قبل الرفع." },
    { question: "هل توجد مزامنة مباشرة مع مسار؟", answer: "لا يصف الموقع حاليًا مزامنة مباشرة. القدرة المؤكدة هي توليد ملف قابل للرفع يدويًا، ولا تعني تكاملًا رسميًا دائمًا." },
    { question: "هل رقيم نظام سحابي؟", answer: "نعم، يتيح للمستخدمين المخولين الوصول إلى السجل المركزي عبر الأجهزة المدعومة بدل حفظ نسخ منفصلة في كل جهاز." },
    { question: "هل يعمل رقيم كاملًا دون إنترنت؟", answer: "العمل السحابي الأساسي يحتاج اتصالًا. لا ينبغي افتراض عمل كامل دون اتصال، وتُحدد أي قدرة Offline بحسب الخاصية والجهاز والنسخة المعلنة." },
    { question: "هل يجب تشغيل جميع الوحدات في اليوم الأول؟", answer: "لا. يمكن الإطلاق تدريجيًا مع تحديد نطاق كل مرحلة والحفاظ على اتساق البيانات بين الوظائف التي تم تفعيلها." },
    { question: "كيف أطلب عرضًا توضيحيًا أو دعمًا؟", answer: "يمكن استعمال صفحة العرض التوضيحي لفهم المسارات المناسبة، وصفحة الدعم لإرسال طلب واضح دون تضمين كلمات مرور أو بيانات حساسة غير ضرورية." },
  ],
  fr: [
    { question: "Qu’est-ce que Raqeem ?", answer: "Raqeem est une plateforme d’exploitation et de gestion pour les écoles privées au Maroc, reliant admissions, scolarité, finance, enseignement, présence, emploi du temps et communication scolaire." },
    { question: "Quels établissements Raqeem accompagne-t-il ?", answer: "Raqeem s’adresse principalement aux écoles privées et aux établissements dont les besoins correspondent aux parcours actuellement disponibles." },
    { question: "Sur quels appareils Raqeem fonctionne-t-il ?", answer: "Raqeem fonctionne sur Web, Windows, Android et iOS, avec une présentation adaptée au rôle, à la tâche et à l’écran." },
    { question: "Peut-on gérer l’école sur mobile et ordinateur ?", answer: "Oui. Le mobile convient au suivi rapide, tandis que les tableaux et opérations administratives longues sont souvent plus confortables sur Web ou Windows." },
    { question: "Comment une demande devient-elle un dossier élève ?", answer: "L’administration contrôle la demande, vérifie les doublons, rattache le parent puis crée après acceptation le dossier élève et la scolarité appropriée." },
    { question: "Que se passe-t-il si le parent existe déjà ?", answer: "Le dossier existant est vérifié puis rattaché afin d’éviter un doublon et de conserver la bonne relation familiale." },
    { question: "Comment organiser frais et encaissements ?", answer: "Le plan définit montants et échéances, tandis que les encaissements réels sont enregistrés séparément avec mode de paiement, affectation, reste et retard." },
    { question: "Peut-on émettre un reçu pour un paiement partiel ?", answer: "Oui. Le reçu reflète le montant réellement encaissé et le solde restant demeure visible." },
    { question: "Comment Raqeem gère-t-il présence et absence ?", answer: "L’état est lié à l’élève, la date et la séance, en distinguant absence, retard et départ anticipé, avec justification après contrôle." },
    { question: "Chaque absence envoie-t-elle automatiquement un message ?", answer: "Cela dépend de la politique et des réglages de l’établissement. L’information doit reposer sur un état validé et le bon destinataire." },
    { question: "Comment Raqeem gère-t-il l’emploi du temps ?", answer: "Il permet de configurer périodes et ressources, construire un brouillon et contrôler les conflits enseignant, classe et salle avant validation et publication." },
    { question: "Raqeem génère-t-il automatiquement tout l’emploi du temps ?", answer: "Il ne faut pas supposer une génération automatique complète. Le site décrit la gestion du brouillon, le contrôle des conflits, la validation et la publication." },
    { question: "Comment fonctionne la communication scolaire ?", answer: "C’est un registre officiel où les rôles définissent qui prépare, révise, valide et reçoit le contenu." },
    { question: "Un enseignant peut-il écrire directement à un parent ?", answer: "Pas en dehors du parcours gouverné. La diffusion aux parents ou élèves passe par la révision et l’approbation prévues." },
    { question: "Comment sont gérés rôles et autorisations ?", answer: "Chaque rôle reçoit des capacités et un périmètre précis pour lire, créer, modifier, supprimer, réviser ou valider." },
    { question: "Masquer un bouton suffit-il à bloquer une action ?", answer: "Non. La protection doit s’appliquer à l’opération et aux données elles-mêmes." },
    { question: "Comment Raqeem isole-t-il les données des écoles ?", answer: "Chaque client travaille dans le périmètre autorisé de son établissement, sans exposition des données ou méthodes à une autre école." },
    { question: "Raqeem compare-t-il les écoles ou partage-t-il leurs pratiques ?", answer: "Non. Les écoles ne sont pas comparées et leurs données ou méthodes ne sont pas transférées, même sous forme anonymisée dans le but de partager des pratiques." },
    { question: "Raqeem gère-t-il les groupes scolaires et plusieurs sites ?", answer: "Oui, dans un cadre administratif réel avec des droits centraux définis, tout en conservant le périmètre propre de chaque site." },
    { question: "Comment les données élèves et familles sont-elles protégées ?", answer: "Par l’isolation, le moindre privilège, la restriction des champs sensibles, la révision des comptes et l’utilisation de données fictives pour les tests." },
    { question: "Peut-on passer d’Excel à Raqeem ?", answer: "Oui, avec inventaire, nettoyage, import pilote, rapprochement des résultats et plan de bascule." },
    { question: "Quelle est la relation entre Raqeem et Massar ?", answer: "Raqeem gère le quotidien et peut générer des fichiers préparés pour le téléversement dans Massar selon le format d’export pris en charge." },
    { question: "Raqeem peut-il générer des fichiers prêts pour Massar ?", answer: "Oui. Le fichier est produit à partir des données contrôlées, puis les champs, lignes et format doivent être vérifiés avant téléversement." },
    { question: "Existe-t-il une synchronisation directe avec Massar ?", answer: "Le site ne décrit pas actuellement de synchronisation directe. La capacité confirmée est la génération d’un fichier téléversé manuellement par un utilisateur autorisé." },
    { question: "Raqeem est-il un système cloud ?", answer: "Oui. Les utilisateurs autorisés accèdent à un registre central depuis les appareils pris en charge au lieu de conserver des copies séparées." },
    { question: "Raqeem fonctionne-t-il entièrement sans Internet ?", answer: "Le fonctionnement cloud principal exige une connexion. Toute capacité hors ligne dépend de la fonction, de l’appareil et de la version publiée." },
    { question: "Faut-il activer tous les modules le premier jour ?", answer: "Non. Le déploiement peut être progressif si le périmètre de chaque phase est clair et les données restent cohérentes." },
    { question: "Comment demander une démonstration ou du support ?", answer: "La page Démonstration permet d’examiner les parcours, et la page Support sert à envoyer une demande claire sans mots de passe ni données sensibles inutiles." },
  ],
  en: [
    { question: "What is Raqeem?", answer: "Raqeem is a school operations and management platform for private schools in Morocco, connecting admissions, enrolment, finance, teaching, attendance, timetables and school communication." },
    { question: "What types of institutions does Raqeem serve?", answer: "Raqeem primarily serves private schools and institutions whose needs match the currently available product journeys." },
    { question: "Which devices does Raqeem support?", answer: "Raqeem works on Web, Windows, Android and iOS, with interfaces adapted to the role, task and screen size." },
    { question: "Can the school be managed from mobile and computer?", answer: "Yes. Mobile suits quick follow-up, while large tables and longer administrative work are usually clearer on Web or Windows." },
    { question: "How does an application become a student record?", answer: "The school reviews the application, checks duplicates, links the guardian and then creates the student record and correct enrolment after acceptance." },
    { question: "What happens when the guardian already exists?", answer: "The existing record is verified and linked rather than creating a duplicate, while preserving the correct family relationship." },
    { question: "How are school fees and collections organised?", answer: "The financial plan defines amounts and due dates, while actual collections are recorded separately with payment method, allocation, remaining and overdue balances." },
    { question: "Can a receipt be issued for a partial payment?", answer: "Yes. The receipt reflects the actual amount received and the remaining balance stays visible." },
    { question: "How does Raqeem manage attendance and absence?", answer: "The status is linked to the student, date and lesson, with absence, lateness and early departure kept distinct and justifications reviewed." },
    { question: "Does every absence trigger an automatic message?", answer: "That depends on school policy and configuration. Any update should use an approved status and the correct linked recipient." },
    { question: "How does Raqeem manage timetables?", answer: "It supports period and resource setup, draft building and teacher, class and room conflict checks before approval and publication." },
    { question: "Does Raqeem fully generate timetables automatically?", answer: "Full automatic generation should not be assumed. The published capability covers draft management, conflict review, approval and publication." },
    { question: "How does school communication work?", answer: "It is an official institution record where roles define who prepares, reviews, approves and receives content." },
    { question: "Can a teacher message a parent directly?", answer: "Not outside the governed journey. Delivery to parents or students follows the school’s review and approval process." },
    { question: "How are roles and permissions managed?", answer: "Each role receives defined capabilities and data scope for viewing, creating, editing, deleting, reviewing or approving." },
    { question: "Is hiding a button enough to block an action?", answer: "No. The permission must protect the operation and data themselves, not only the interface." },
    { question: "How does Raqeem isolate school data?", answer: "Each customer works inside its authorised institution scope, without exposing one school’s data, settings or methods to another." },
    { question: "Does Raqeem compare schools or share their practices?", answer: "No. Schools are not compared and their data or practices are not transferred, including anonymised or aggregated use intended to share methods." },
    { question: "Does Raqeem support school groups and multiple branches?", answer: "Yes, within a genuine administrative relationship and explicit central permissions, while each branch keeps its own scope." },
    { question: "How are student and family data protected?", answer: "Through institution isolation, least privilege, restricted sensitive fields, account review and fictional data in testing." },
    { question: "Can a school move from Excel to Raqeem?", answer: "Yes, through inventory, cleaning, a pilot import, reconciliation and a controlled cutover plan." },
    { question: "What is the relationship between Raqeem and Massar?", answer: "Raqeem manages daily operations and can generate files prepared for upload to Massar according to the supported export format." },
    { question: "Can Raqeem generate files ready for Massar upload?", answer: "Yes. It can produce prepared files from reviewed data, with records, required fields and format checked before upload." },
    { question: "Is there direct synchronisation with Massar?", answer: "The website does not currently describe direct synchronisation. The confirmed capability is a file that an authorised user reviews and uploads manually." },
    { question: "Is Raqeem a cloud system?", answer: "Yes. Authorised users access a central record from supported devices instead of maintaining separate copies." },
    { question: "Does Raqeem work fully without internet access?", answer: "Core cloud work requires connectivity. Any offline capability depends on the specific feature, device and published version." },
    { question: "Must every module launch on day one?", answer: "No. Rollout can be phased when each phase has a clear scope and data remains coherent." },
    { question: "How do I request a demo or support?", answer: "Use the Demo page to review relevant journeys and the Support page for a clear request without passwords or unnecessary sensitive data." },
  ],
  es: [
    { question: "¿Qué es Raqeem?", answer: "Raqeem es una plataforma de operaciones y gestión para colegios privados en Marruecos que conecta admisión, escolaridad, finanzas, enseñanza, asistencia, horarios y comunicación escolar." },
    { question: "¿Qué instituciones atiende Raqeem?", answer: "Raqeem se dirige principalmente a colegios privados y a instituciones cuyas necesidades coinciden con los recorridos disponibles." },
    { question: "¿En qué dispositivos funciona Raqeem?", answer: "Raqeem funciona en Web, Windows, Android e iOS, con interfaces adaptadas al rol, la tarea y el tamaño de pantalla." },
    { question: "¿Se puede gestionar el colegio desde móvil y ordenador?", answer: "Sí. El móvil sirve para seguimiento rápido y el ordenador suele ser mejor para tablas y tareas administrativas largas." },
    { question: "¿Cómo pasa una solicitud a expediente de alumno?", answer: "El colegio revisa la solicitud, comprueba duplicados, vincula a la familia y crea el expediente y la escolaridad correctos tras aceptar." },
    { question: "¿Qué ocurre si el familiar ya existe?", answer: "Se verifica y vincula el registro existente en lugar de crear un duplicado, manteniendo la relación familiar correcta." },
    { question: "¿Cómo se organizan cuotas y cobros?", answer: "El plan define importes y vencimientos, mientras los cobros reales se registran aparte con método, asignación, pendiente y vencido." },
    { question: "¿Se puede emitir un recibo por un pago parcial?", answer: "Sí. El recibo refleja el importe recibido y mantiene visible el saldo pendiente." },
    { question: "¿Cómo gestiona Raqeem asistencia y ausencia?", answer: "El estado se vincula al alumno, fecha y clase, diferenciando ausencia, retraso y salida anticipada, con justificación revisada." },
    { question: "¿Cada ausencia envía un mensaje automático?", answer: "Depende de la política y configuración del centro. La información debe usar un estado aprobado y el destinatario correcto." },
    { question: "¿Cómo gestiona Raqeem los horarios?", answer: "Permite configurar periodos y recursos, construir un borrador y revisar conflictos de docente, clase y aula antes de aprobar y publicar." },
    { question: "¿Raqeem genera automáticamente todo el horario?", answer: "No debe suponerse generación automática completa. La capacidad publicada cubre borrador, conflictos, aprobación y publicación." },
    { question: "¿Cómo funciona la comunicación escolar?", answer: "Es un registro oficial donde los roles definen quién prepara, revisa, aprueba y recibe el contenido." },
    { question: "¿Puede un docente escribir directamente a una familia?", answer: "No fuera del recorrido controlado. La entrega a familias o alumnos sigue revisión y aprobación del centro." },
    { question: "¿Cómo se gestionan roles y permisos?", answer: "Cada rol recibe capacidades y ámbito de datos para ver, crear, editar, eliminar, revisar o aprobar." },
    { question: "¿Ocultar un botón bloquea una acción?", answer: "No. El permiso debe proteger la operación y los datos, no solo la interfaz." },
    { question: "¿Cómo aísla Raqeem los datos de los colegios?", answer: "Cada cliente trabaja dentro del ámbito autorizado de su institución, sin exponer datos, ajustes o métodos a otro colegio." },
    { question: "¿Raqeem compara colegios o comparte sus prácticas?", answer: "No. No se comparan colegios ni se transfieren datos o prácticas, incluso de forma anónima o agregada para compartir métodos." },
    { question: "¿Raqeem admite grupos escolares y varias sedes?", answer: "Sí, dentro de una relación administrativa real y permisos centrales explícitos, conservando el ámbito de cada sede." },
    { question: "¿Cómo se protegen los datos de alumnos y familias?", answer: "Con aislamiento, mínimo privilegio, campos sensibles restringidos, revisión de cuentas y datos ficticios en pruebas." },
    { question: "¿Se puede pasar de Excel a Raqeem?", answer: "Sí, mediante inventario, limpieza, importación piloto, conciliación y un cambio controlado." },
    { question: "¿Qué relación existe entre Raqeem y Massar?", answer: "Raqeem gestiona el trabajo diario y puede generar archivos preparados para subir a Massar según el formato de exportación admitido." },
    { question: "¿Raqeem puede generar archivos listos para Massar?", answer: "Sí. Produce archivos preparados desde datos revisados, y se comprueban registros, campos y formato antes de subirlos." },
    { question: "¿Existe sincronización directa con Massar?", answer: "El sitio no describe actualmente sincronización directa. La capacidad confirmada es un archivo que el usuario autorizado revisa y sube manualmente." },
    { question: "¿Raqeem es un sistema en la nube?", answer: "Sí. Los usuarios autorizados acceden a un registro central desde dispositivos compatibles, sin mantener copias separadas." },
    { question: "¿Raqeem funciona completamente sin Internet?", answer: "El trabajo principal en la nube necesita conexión. Cualquier capacidad sin conexión depende de la función, dispositivo y versión publicada." },
    { question: "¿Hay que activar todos los módulos el primer día?", answer: "No. El despliegue puede ser gradual si cada fase tiene un alcance claro y los datos siguen coherentes." },
    { question: "¿Cómo solicito una demostración o soporte?", answer: "Usa la página Demostración para revisar recorridos y la página Soporte para enviar una solicitud clara sin contraseñas ni datos sensibles innecesarios." },
  ],
};
