import type { Locale } from "@/i18n/routing";

export type PrivacySection = {
  title: string;
  text: string;
};

type PrivacyPolicy = {
  title: string;
  updated: string;
  sections: PrivacySection[];
};

const company = "Genius Step SARL, 37 Rue 40, Aouama Zemmouri, Lot 271, 90080 Tanger, Maroc";
const email = "contact@raqeem.ma";

export const privacyPolicies: Record<Locale, PrivacyPolicy> = {
  fr: {
    title: "Politique de confidentialité de Raqeem",
    updated: "Dernière mise à jour : 31 juillet 2026",
    sections: [
      { title: "1. Objet de la présente politique", text: "La présente politique explique comment les données à caractère personnel sont traitées lors de l’utilisation du site officiel Raqeem, de l’application mobile Raqeem, de la plateforme web Raqeem ainsi que des formulaires de contact, de demande de démonstration et d’assistance. L’utilisation de la plateforme par un établissement est également régie par le contrat conclu entre cet établissement et Genius Step SARL." },
      { title: "2. Identité des intervenants", text: `Raqeem est édité et fourni par ${company}. Contact : ${email}. Dans le cadre de l’utilisation scolaire, l’établissement éducatif détermine généralement les finalités et les conditions d’utilisation des données de ses élèves, responsables légaux, membres du personnel et autres utilisateurs. Genius Step SARL traite ces données afin de fournir, sécuriser, maintenir et assister le service conformément aux instructions et accords conclus avec l’établissement.` },
      { title: "3. Données traitées", text: "Selon le rôle de l’utilisateur et les fonctionnalités activées, Raqeem peut traiter des données d’identification et de compte, des données relatives aux élèves et aux familles, des données scolaires et pédagogiques, des données professionnelles du personnel, des données administratives et financières, des messages, annonces, documents et pièces jointes, ainsi que des données techniques nécessaires au fonctionnement et à la sécurité du service." },
      { title: "4. Finalités du traitement", text: "Les données sont traitées afin d’administrer les accès autorisés, fournir les fonctionnalités demandées, gérer la scolarité, l’assiduité, les devoirs, les résultats, les emplois du temps et les communications, présenter les informations administratives ou financières autorisées, assurer l’assistance, maintenir la sécurité et diagnostiquer les erreurs. Raqeem ne vend pas les données personnelles." },
      { title: "5. Base et autorisation du traitement", text: "Les données sont traitées, selon le contexte, pour fournir le service demandé, exécuter le contrat conclu avec l’établissement, accomplir les missions éducatives et administratives autorisées, respecter une obligation légale, assurer la sécurité du service ou sur la base du consentement lorsqu’il est requis." },
      { title: "6. Données des enfants et des mineurs", text: "Raqeem peut traiter des données concernant des élèves mineurs. Ces données sont fournies ou administrées par l’établissement, les représentants légaux ou les utilisateurs autorisés et ne doivent être utilisées que pour les finalités scolaires, administratives, pédagogiques ou de sécurité prévues." },
      { title: "7. Partage et destinataires", text: "Les données peuvent être accessibles aux utilisateurs autorisés selon leur rôle et leur périmètre, aux représentants légaux pour les enfants auxquels ils sont rattachés, au personnel technique autorisé lorsque cela est nécessaire, aux prestataires indispensables dans la limite de leurs missions et aux autorités compétentes lorsque la loi l’impose. Les données d’une école ne sont pas accessibles à une autre école." },
      { title: "8. Notifications", text: "L’application peut envoyer des notifications concernant l’assiduité, les devoirs, les résultats, les emplois du temps, les annonces, les messages et d’autres événements scolaires autorisés. L’utilisateur peut gérer certaines préférences dans l’application ou dans les réglages de son appareil." },
      { title: "9. Autorisations de l’appareil", text: "Selon les fonctions utilisées, l’application peut demander l’accès aux notifications, à l’appareil photo, aux photos ou fichiers afin d’ajouter des pièces jointes ou de téléverser des documents. Ces autorisations ne sont demandées que lorsqu’elles sont nécessaires et peuvent être gérées dans les réglages de l’appareil." },
      { title: "10. Données techniques et sécurité", text: "Raqeem peut traiter des informations techniques telles que le type d’appareil, la version du système, la version de l’application, les journaux d’erreurs, les identifiants de session et les informations nécessaires à la prévention des accès non autorisés. Des mesures techniques et organisationnelles sont mises en œuvre pour protéger les données." },
      { title: "11. Conservation des données", text: "Les données sont conservées pendant la durée nécessaire à la fourniture du service, au respect des obligations contractuelles ou légales et à la résolution des litiges. À la fin de la relation avec l’établissement, les données sont supprimées, restituées ou anonymisées selon les accords applicables et les obligations légales." },
      { title: "12. Suppression du compte", text: `Lorsqu’un compte est créé ou administré par un établissement, la demande de suppression doit d’abord être adressée à cet établissement. Pour les comptes ou demandes gérés directement par Genius Step SARL, la demande peut être envoyée à ${email}. La suppression peut être limitée lorsque certaines données doivent être conservées pour des raisons légales, contractuelles, comptables ou de sécurité.` },
      { title: "13. Droits des utilisateurs", text: "Sous réserve de la législation applicable, les personnes concernées peuvent demander l’accès à leurs données, leur rectification, leur mise à jour, leur limitation ou leur suppression. Les demandes relatives aux données scolaires doivent généralement être adressées à l’établissement concerné." },
      { title: "14. Analytique", text: "Lorsque des outils d’analyse sont activés, ils servent à mesurer l’utilisation générale du site ou de l’application, améliorer les performances et détecter les erreurs. Ils ne doivent pas recevoir le contenu des messages, les résultats scolaires ou d’autres données scolaires sensibles à des fins publicitaires." },
      { title: "15. Prestataires techniques", text: "Genius Step SARL peut recourir à des prestataires d’hébergement, de messagerie, de notifications, de surveillance technique ou d’assistance. Ils ne peuvent traiter les données que dans la mesure nécessaire à leurs missions et selon des engagements appropriés de confidentialité et de sécurité." },
      { title: "16. Transferts de données", text: "Lorsque le recours à un prestataire implique un traitement en dehors du Maroc, Genius Step SARL veille à appliquer les garanties contractuelles, organisationnelles et techniques requises par la réglementation applicable." },
      { title: "17. Mise à jour de la politique", text: "La présente politique peut être mise à jour afin de refléter les évolutions du service, de la réglementation ou de nos pratiques. La date de la dernière mise à jour est indiquée en haut de la page." },
      { title: "18. Contact", text: `Pour toute question relative à la confidentialité : ${company}. E-mail : ${email}. Pour une demande concernant un dossier scolaire, un élève, un responsable légal ou un compte créé par un établissement, contactez d’abord l’administration de l’établissement concerné.` },
    ],
  },
  ar: {
    title: "سياسة خصوصية رقيم",
    updated: "آخر تحديث: 31 يوليو 2026",
    sections: [
      { title: "1. الغرض من هذه السياسة", text: "توضح هذه السياسة كيفية معالجة البيانات ذات الطابع الشخصي عند استخدام الموقع الرسمي لرقيم، وتطبيق رقيم للهاتف، ومنصة رقيم على الويب، ونماذج التواصل وطلب العرض التوضيحي والدعم. كما يخضع استعمال المؤسسة التعليمية للمنصة للعقد المبرم بينها وبين Genius Step SARL." },
      { title: "2. الأطراف المتدخلة", text: `تُقدَّم منصة رقيم وتُشغَّل من طرف ${company}. البريد الإلكتروني: ${email}. تحدد المؤسسة التعليمية عادة أغراض وشروط معالجة بيانات تلاميذها وأولياء أمورهم وطاقمها وباقي مستخدميها، بينما تعالج Genius Step SARL هذه البيانات لتقديم الخدمة وتأمينها وصيانتها وتوفير الدعم وفق تعليمات المؤسسة والاتفاقات المبرمة معها.` },
      { title: "3. البيانات التي تتم معالجتها", text: "بحسب دور المستخدم والخصائص التي فعّلتها المؤسسة، قد تعالج رقيم بيانات الهوية والحساب، وبيانات التلاميذ والأسر، والبيانات المدرسية والتربوية، والبيانات المهنية للطاقم، والبيانات الإدارية والمالية، والرسائل والإعلانات والوثائق والمرفقات، والبيانات التقنية اللازمة لتشغيل الخدمة وتأمينها." },
      { title: "4. أغراض المعالجة", text: "تُعالج البيانات لإدارة صلاحيات الوصول، وتقديم الخصائص المطلوبة، وتدبير التمدرس والحضور والغياب والواجبات والنتائج واستعمال الزمن والتواصل، وعرض المعلومات الإدارية أو المالية المصرح بها، وتقديم الدعم، وحماية الحسابات والخدمة، وتشخيص الأخطاء. لا تبيع رقيم البيانات الشخصية." },
      { title: "5. أساس المعالجة والترخيص بها", text: "تُعالج البيانات، بحسب السياق، لتقديم الخدمة المطلوبة، وتنفيذ العقد المبرم مع المؤسسة، وإنجاز المهام التربوية والإدارية المصرح بها، واحترام الالتزامات القانونية، وضمان أمن الخدمة، أو استنادًا إلى الموافقة عندما تكون مطلوبة." },
      { title: "6. بيانات الأطفال والقاصرين", text: "قد تعالج رقيم بيانات تخص تلاميذ قاصرين. وتوفر هذه البيانات أو تديرها المؤسسة أو أولياء الأمور أو المستخدمون المخولون، ولا يجوز استعمالها إلا للأغراض المدرسية أو الإدارية أو التربوية أو الأمنية المحددة." },
      { title: "7. مشاركة البيانات والجهات المستفيدة", text: "يمكن أن تصل إلى البيانات الجهات المخولة داخل المؤسسة بحسب الدور والنطاق، وأولياء الأمور بالنسبة إلى أبنائهم المرتبطين بهم بصورة صحيحة، والطاقم التقني المخول عند الضرورة، ومقدمو الخدمات الضرورية في حدود مهامهم، والسلطات المختصة عندما يفرض القانون ذلك. لا تكون بيانات مدرسة متاحة لأي مدرسة أخرى." },
      { title: "8. الإشعارات", text: "قد يرسل التطبيق إشعارات تتعلق بالحضور والغياب والواجبات والنتائج واستعمال الزمن والإعلانات والرسائل وغيرها من الأحداث المدرسية المصرح بها. ويمكن للمستخدم إدارة بعض التفضيلات من التطبيق أو من إعدادات الجهاز." },
      { title: "9. صلاحيات الجهاز", text: "بحسب الوظائف المستعملة، قد يطلب التطبيق صلاحية الإشعارات أو الكاميرا أو الصور أو الملفات لإضافة المرفقات أو رفع الوثائق. ولا تُطلب هذه الصلاحيات إلا عند الحاجة ويمكن التحكم فيها من إعدادات الجهاز." },
      { title: "10. البيانات التقنية والأمان", text: "قد تعالج رقيم معلومات تقنية مثل نوع الجهاز وإصدار النظام وإصدار التطبيق وسجلات الأخطاء ومعرفات الجلسة والمعلومات اللازمة لمنع الوصول غير المصرح به. وتُطبّق تدابير تقنية وتنظيمية لحماية البيانات." },
      { title: "11. الاحتفاظ بالبيانات", text: "تُحتفظ البيانات طوال المدة اللازمة لتقديم الخدمة، وتنفيذ الالتزامات التعاقدية أو القانونية، وتسوية النزاعات. وعند انتهاء العلاقة مع المؤسسة، تُحذف البيانات أو تُعاد أو تُجعل مجهولة الهوية بحسب الاتفاقات المطبقة والالتزامات القانونية." },
      { title: "12. حذف الحساب", text: `عندما تنشئ المؤسسة الحساب أو تديره، يجب توجيه طلب الحذف أولًا إلى المؤسسة. أما الحسابات أو الطلبات التي تديرها Genius Step SARL مباشرة فيمكن إرسال طلب حذفها إلى ${email}. وقد تُقيَّد عملية الحذف عندما يلزم الاحتفاظ ببعض البيانات لأسباب قانونية أو تعاقدية أو محاسبية أو أمنية.` },
      { title: "13. حقوق المستخدمين", text: "مع مراعاة القانون المطبق، يمكن للأشخاص المعنيين طلب الوصول إلى بياناتهم أو تصحيحها أو تحديثها أو تقييد معالجتها أو حذفها. وتوجَّه الطلبات المتعلقة بالبيانات المدرسية عادة إلى المؤسسة المعنية." },
      { title: "14. التحليلات", text: "عند تفعيل أدوات التحليل، تُستخدم لقياس الاستعمال العام للموقع أو التطبيق وتحسين الأداء واكتشاف الأخطاء، ولا ينبغي أن تتلقى محتوى الرسائل أو النتائج الدراسية أو غيرها من البيانات المدرسية الحساسة لأغراض إعلانية." },
      { title: "15. مقدمو الخدمات التقنية", text: "يمكن لـGenius Step SARL الاستعانة بمقدمي خدمات الاستضافة والبريد والإشعارات والمراقبة التقنية والدعم. ولا يجوز لهم معالجة البيانات إلا بالقدر اللازم لمهامهم ووفق التزامات مناسبة بالسرية والأمان." },
      { title: "16. نقل البيانات", text: "عندما يستلزم اللجوء إلى مقدم خدمة معالجة البيانات خارج المغرب، تحرص Genius Step SARL على تطبيق الضمانات التعاقدية والتنظيمية والتقنية التي يقتضيها القانون المطبق." },
      { title: "17. تحديث السياسة", text: "قد تُحدّث هذه السياسة لتعكس تطور الخدمة أو القوانين أو ممارساتنا. ويظهر تاريخ آخر تحديث في أعلى الصفحة." },
      { title: "18. التواصل", text: `لأي سؤال متعلق بالخصوصية: ${company}. البريد الإلكتروني: ${email}. أما الطلب المتعلق بملف مدرسي أو تلميذ أو ولي أمر أو حساب أنشأته مؤسسة تعليمية، فيُرجى التواصل أولًا مع إدارة المؤسسة المعنية.` },
    ],
  },
  en: {
    title: "Raqeem Privacy Policy",
    updated: "Last updated: July 31, 2026",
    sections: [
      { title: "1. Purpose of this policy", text: "This policy explains how personal data is processed when using the official Raqeem website, the Raqeem mobile application, the Raqeem web platform, and contact, demo request, and support forms. An educational institution’s use of the platform is also governed by its agreement with Genius Step SARL." },
      { title: "2. Parties involved", text: `Raqeem is published and provided by ${company}. Email: ${email}. In the school context, the educational institution generally determines the purposes and conditions for processing the data of its students, guardians, staff, and other users. Genius Step SARL processes that data to provide, secure, maintain, and support the service in accordance with the institution’s instructions and agreements.` },
      { title: "3. Data processed", text: "Depending on the user’s role and the features enabled by the institution, Raqeem may process identity and account data, student and family data, academic and educational data, staff professional data, administrative and financial data, messages, announcements, documents and attachments, and technical data required to operate and secure the service." },
      { title: "4. Purposes of processing", text: "Data is processed to manage authorized access, provide requested features, manage schooling, attendance, homework, results, timetables and communications, display authorized administrative or financial information, provide support, protect accounts and the service, and diagnose errors. Raqeem does not sell personal data." },
      { title: "5. Legal basis and authorization", text: "Depending on the context, data is processed to provide the requested service, perform the agreement with the institution, carry out authorized educational and administrative activities, comply with legal obligations, protect the service, or on the basis of consent where required." },
      { title: "6. Children’s and minors’ data", text: "Raqeem may process data relating to minor students. Such data is provided or managed by the institution, legal guardians, or authorized users and must only be used for the defined school, administrative, educational, or security purposes." },
      { title: "7. Sharing and recipients", text: "Data may be available to authorized users according to their role and scope, to guardians for children properly linked to them, to authorized technical staff when necessary, to essential service providers within the limits of their duties, and to competent authorities when required by law. One school’s data is not made available to another school." },
      { title: "8. Notifications", text: "The application may send notifications about attendance, homework, results, timetables, announcements, messages, and other authorized school events. Users can manage certain preferences in the application or their device settings." },
      { title: "9. Device permissions", text: "Depending on the functions used, the application may request access to notifications, the camera, photos, or files to add attachments or upload documents. Permissions are requested only when needed and can be managed in device settings." },
      { title: "10. Technical data and security", text: "Raqeem may process technical information such as device type, operating system version, application version, error logs, session identifiers, and information required to prevent unauthorized access. Technical and organizational measures are applied to protect data." },
      { title: "11. Data retention", text: "Data is retained for as long as necessary to provide the service, meet contractual or legal obligations, and resolve disputes. When the relationship with an institution ends, data is deleted, returned, or anonymized in accordance with applicable agreements and legal obligations." },
      { title: "12. Account deletion", text: `When an account is created or managed by an institution, deletion requests should first be sent to that institution. For accounts or requests managed directly by Genius Step SARL, a deletion request may be sent to ${email}. Deletion may be limited where certain data must be retained for legal, contractual, accounting, or security reasons.` },
      { title: "13. User rights", text: "Subject to applicable law, individuals may request access to, correction, updating, restriction, or deletion of their data. Requests relating to school records should generally be addressed to the relevant institution." },
      { title: "14. Analytics", text: "Where analytics tools are enabled, they are used to measure general website or application usage, improve performance, and detect errors. They should not receive message content, academic results, or other sensitive school data for advertising purposes." },
      { title: "15. Technical service providers", text: "Genius Step SARL may use hosting, email, notification, technical monitoring, or support providers. They may process data only to the extent necessary for their duties and under appropriate confidentiality and security commitments." },
      { title: "16. Data transfers", text: "Where a service provider’s involvement requires processing outside Morocco, Genius Step SARL applies the contractual, organizational, and technical safeguards required by applicable law." },
      { title: "17. Policy updates", text: "This policy may be updated to reflect changes in the service, applicable law, or our practices. The latest update date appears at the top of the page." },
      { title: "18. Contact", text: `For privacy questions: ${company}. Email: ${email}. For a request concerning a school record, student, guardian, staff member, or account created by an educational institution, please contact the relevant institution first.` },
    ],
  },
  es: {
    title: "Política de privacidad de Raqeem",
    updated: "Última actualización: 31 de julio de 2026",
    sections: [
      { title: "1. Objeto de esta política", text: "Esta política explica cómo se tratan los datos personales al utilizar el sitio web oficial de Raqeem, la aplicación móvil Raqeem, la plataforma web Raqeem y los formularios de contacto, solicitud de demostración y asistencia. El uso de la plataforma por un centro educativo también se rige por el contrato celebrado con Genius Step SARL." },
      { title: "2. Partes intervinientes", text: `Raqeem es publicado y prestado por ${company}. Correo electrónico: ${email}. En el contexto escolar, el centro educativo determina normalmente las finalidades y condiciones del tratamiento de los datos de sus alumnos, tutores legales, personal y demás usuarios. Genius Step SARL trata esos datos para prestar, proteger, mantener y asistir el servicio conforme a las instrucciones y acuerdos del centro.` },
      { title: "3. Datos tratados", text: "Según el rol del usuario y las funciones activadas por el centro, Raqeem puede tratar datos de identidad y cuenta, datos de alumnos y familias, datos académicos y pedagógicos, datos profesionales del personal, datos administrativos y financieros, mensajes, anuncios, documentos y archivos adjuntos, y datos técnicos necesarios para el funcionamiento y la seguridad del servicio." },
      { title: "4. Finalidades del tratamiento", text: "Los datos se tratan para gestionar accesos autorizados, prestar las funciones solicitadas, gestionar la escolaridad, asistencia, tareas, resultados, horarios y comunicaciones, mostrar información administrativa o financiera autorizada, proporcionar asistencia, proteger las cuentas y el servicio y diagnosticar errores. Raqeem no vende datos personales." },
      { title: "5. Base y autorización del tratamiento", text: "Según el contexto, los datos se tratan para prestar el servicio solicitado, ejecutar el contrato con el centro, realizar actividades educativas y administrativas autorizadas, cumplir obligaciones legales, proteger el servicio o sobre la base del consentimiento cuando sea necesario." },
      { title: "6. Datos de niños y menores", text: "Raqeem puede tratar datos de alumnos menores de edad. Estos datos son proporcionados o administrados por el centro, los representantes legales o usuarios autorizados y solo deben utilizarse para los fines escolares, administrativos, pedagógicos o de seguridad definidos." },
      { title: "7. Comunicación y destinatarios", text: "Los datos pueden estar disponibles para usuarios autorizados según su rol y ámbito, para los tutores de los menores correctamente vinculados, para el personal técnico autorizado cuando sea necesario, para proveedores esenciales dentro de los límites de sus funciones y para las autoridades competentes cuando la ley lo exija. Los datos de un centro no se ponen a disposición de otro centro." },
      { title: "8. Notificaciones", text: "La aplicación puede enviar notificaciones sobre asistencia, tareas, resultados, horarios, anuncios, mensajes y otros eventos escolares autorizados. El usuario puede gestionar determinadas preferencias en la aplicación o en los ajustes del dispositivo." },
      { title: "9. Permisos del dispositivo", text: "Según las funciones utilizadas, la aplicación puede solicitar acceso a las notificaciones, la cámara, las fotos o los archivos para añadir adjuntos o cargar documentos. Los permisos solo se solicitan cuando son necesarios y pueden administrarse desde los ajustes del dispositivo." },
      { title: "10. Datos técnicos y seguridad", text: "Raqeem puede tratar información técnica como el tipo de dispositivo, la versión del sistema operativo, la versión de la aplicación, registros de errores, identificadores de sesión e información necesaria para prevenir accesos no autorizados. Se aplican medidas técnicas y organizativas para proteger los datos." },
      { title: "11. Conservación de los datos", text: "Los datos se conservan durante el tiempo necesario para prestar el servicio, cumplir obligaciones contractuales o legales y resolver controversias. Cuando finaliza la relación con el centro, los datos se eliminan, devuelven o anonimizan conforme a los acuerdos aplicables y las obligaciones legales." },
      { title: "12. Eliminación de la cuenta", text: `Cuando una cuenta es creada o administrada por un centro, la solicitud de eliminación debe dirigirse primero a dicho centro. Para cuentas o solicitudes gestionadas directamente por Genius Step SARL, la solicitud puede enviarse a ${email}. La eliminación puede limitarse cuando determinados datos deban conservarse por motivos legales, contractuales, contables o de seguridad.` },
      { title: "13. Derechos de los usuarios", text: "Con sujeción a la legislación aplicable, las personas pueden solicitar el acceso, rectificación, actualización, limitación o eliminación de sus datos. Las solicitudes relativas a expedientes escolares deben dirigirse normalmente al centro correspondiente." },
      { title: "14. Analítica", text: "Cuando se activan herramientas de analítica, se utilizan para medir el uso general del sitio web o la aplicación, mejorar el rendimiento y detectar errores. No deben recibir el contenido de mensajes, resultados académicos u otros datos escolares sensibles con fines publicitarios." },
      { title: "15. Proveedores técnicos", text: "Genius Step SARL puede recurrir a proveedores de alojamiento, correo electrónico, notificaciones, supervisión técnica o asistencia. Solo pueden tratar los datos en la medida necesaria para sus funciones y con compromisos adecuados de confidencialidad y seguridad." },
      { title: "16. Transferencias de datos", text: "Cuando la intervención de un proveedor implique tratamiento fuera de Marruecos, Genius Step SARL aplica las garantías contractuales, organizativas y técnicas exigidas por la normativa aplicable." },
      { title: "17. Actualización de la política", text: "Esta política puede actualizarse para reflejar cambios en el servicio, la normativa aplicable o nuestras prácticas. La fecha de la última actualización figura en la parte superior de la página." },
      { title: "18. Contacto", text: `Para consultas sobre privacidad: ${company}. Correo electrónico: ${email}. Para solicitudes relativas a un expediente escolar, alumno, tutor, miembro del personal o cuenta creada por un centro educativo, contacte primero con el centro correspondiente.` },
    ],
  },
};
