import type { CatalogGuideContent } from "@/content/guide-types";
import type { Locale } from "@/i18n/routing";

export const attendanceAbsenceParentUpdatesGuide: Record<Locale, CatalogGuideContent> = {
  ar: {
    slug: "attendance-absence-parent-updates",
    category: "دليل الحضور والغياب",
    title: "كيف تنظم المدرسة الحضور والغياب وإشعار أولياء الأمور؟",
    description: "مسار واضح لتسجيل الحضور والغياب والتأخر والتبرير، ثم متابعة الحالة وإشعار الأسرة وفق سياسة المؤسسة.",
    directAnswerTitle: "الإجابة المباشرة",
    directAnswer: "يبدأ المسار بتسجيل حالة التلميذ في الحصة أو اليوم الصحيح، ثم مراجعة الغياب أو التأخر وإضافة التبرير عند توفره. بعد تثبيت الحالة تستطيع الإدارة متابعة الحالات التي تحتاج تدخلًا وإرسال إشعار مدرسي إلى ولي الأمر وفق الصلاحيات والسياسة المعتمدة، دون تحويل الإشعار إلى محادثة شخصية غير محكومة.",
    updatedLabel: "آخر مراجعة: 3 أغسطس 2026",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    readingTime: "قراءة في 6 دقائق",
    sections: [
      { title: "سجل الحالة في سياقها الصحيح", paragraphs: ["يجب ربط الحضور أو الغياب بالتلميذ والتاريخ والحصة أو الفترة المعنية، مع التمييز بين الغياب والتأخر والمغادرة المبكرة.", "لا ينبغي تعديل حالة قديمة دون صلاحية أو سبب واضح، لأن سجل الحضور يؤثر في المتابعة الإدارية والتربوية."] },
      { title: "راجع التبرير قبل إغلاق الحالة", paragraphs: ["يمكن ربط التبرير بالحالة الأصلية مع تاريخ المراجعة والجهة التي اعتمدته، بدل حذف أثر الغياب أو إنشاء سجل منفصل غير مرتبط.", "تظل الحالات غير المبررة أو المتكررة ظاهرة للإدارة حتى تتخذ الإجراء المناسب."] },
      { title: "أشعر الأسرة ضمن التواصل المدرسي", paragraphs: ["يصل الإشعار إلى ولي الأمر المرتبط بالتلميذ فقط، وبالمحتوى الذي تسمح به سياسة المؤسسة.", "الإشعار ينقل الحالة المعتمدة ولا يفتح قناة مباشرة غير خاضعة للمراجعة بين الأستاذ والأسرة."] },
    ],
    checklistTitle: "ضوابط المسار",
    checklist: ["تحديد التاريخ والحصة والتلميذ بدقة.", "فصل الغياب والتأخر والمغادرة المبكرة.", "ربط التبرير بالحالة الأصلية.", "تحديد من يراجع ومن يعتمد.", "إشعار ولي الأمر المرتبط فقط وفق السياسة."],
    faqTitle: "أسئلة مرتبطة",
    faq: [
      { question: "هل كل غياب يرسل إشعارًا تلقائيًا؟", answer: "يعتمد ذلك على إعداد وسياسة المؤسسة. المهم أن يستند الإشعار إلى حالة صحيحة ومعتمدة وألا يرسل إلى مستلم غير مرتبط بالتلميذ." },
      { question: "هل التبرير يحذف الغياب؟", answer: "لا. الأفضل أن يبقى سجل الغياب موجودًا وتضاف إليه حالة التبرير وقرار المراجعة." },
    ],
    relatedTitle: "صفحات مرتبطة",
    relatedLinks: [
      { href: "/roles/teachers", title: "مساحة الأستاذ", description: "تسجيل المتابعة ضمن الأقسام والصلاحيات الممنوحة." },
      { href: "/roles/parents", title: "مساحة ولي الأمر", description: "متابعة الأبناء والإشعارات المدرسية المرتبطة بهم." },
      { href: "/guides/governed-school-communication", title: "التواصل المدرسي المحكوم", description: "كيف تمر الرسائل والإشعارات تحت إشراف المؤسسة." },
    ],
    ctaTitle: "شاهد مسار الحضور داخل رقيم",
    ctaDescription: "يعرض الفريق التسجيل والمراجعة والتبرير والإشعار باستخدام بيانات تجريبية وأدوار واضحة.",
    ctaButton: "اطلب عرضًا توضيحيًا",
  },
  fr: {
    slug: "attendance-absence-parent-updates",
    category: "Guide de présence",
    title: "Comment gérer présence, absence et information des parents ?",
    description: "Un parcours clair pour enregistrer présence, absence, retard et justification, puis informer la famille selon la politique de l’établissement.",
    directAnswerTitle: "Réponse directe",
    directAnswer: "Le parcours commence par l’enregistrement de l’état de l’élève dans la bonne séance ou journée. L’absence ou le retard est ensuite contrôlé et peut recevoir une justification. Une fois l’état confirmé, l’administration suit les cas nécessitant une action et informe le parent autorisé selon la politique de l’établissement, sans ouvrir une conversation personnelle non gouvernée.",
    updatedLabel: "Dernière révision : 3 août 2026",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    readingTime: "6 minutes de lecture",
    sections: [
      { title: "Enregistrer l’état dans le bon contexte", paragraphs: ["La présence doit être liée à l’élève, la date et la séance ou période concernée, en distinguant absence, retard et départ anticipé.", "Une modification ancienne doit rester limitée aux personnes autorisées et accompagnée d’un motif clair."] },
      { title: "Contrôler la justification", paragraphs: ["La justification doit rester liée à l’absence d’origine avec la date et la personne qui l’a examinée.", "Les situations non justifiées ou répétées restent visibles pour le suivi administratif."] },
      { title: "Informer la famille dans le cadre scolaire", paragraphs: ["L’information est adressée uniquement au parent lié à l’élève et selon la politique de l’établissement.", "Elle transmet un état validé sans créer de messagerie directe non contrôlée entre enseignant et famille."] },
    ],
    checklistTitle: "Contrôles du parcours",
    checklist: ["Identifier date, séance et élève.", "Distinguer absence, retard et départ anticipé.", "Rattacher la justification à l’état initial.", "Définir qui contrôle et valide.", "Informer uniquement le parent autorisé."],
    faqTitle: "Questions associées",
    faq: [
      { question: "Chaque absence déclenche-t-elle automatiquement un message ?", answer: "Cela dépend de la politique et des réglages de l’établissement. L’information doit toujours reposer sur un état correct et validé." },
      { question: "Une justification supprime-t-elle l’absence ?", answer: "Non. L’absence reste dans l’historique et reçoit un état de justification et une décision de contrôle." },
    ],
    relatedTitle: "Pages associées",
    relatedLinks: [
      { href: "/roles/teachers", title: "Espace enseignant", description: "Suivi dans les classes et le périmètre autorisés." },
      { href: "/roles/parents", title: "Espace parents", description: "Suivi des enfants et informations scolaires associées." },
      { href: "/guides/governed-school-communication", title: "Communication scolaire gouvernée", description: "Le parcours des messages sous contrôle de l’établissement." },
    ],
    ctaTitle: "Voir le parcours de présence dans Raqeem",
    ctaDescription: "La démonstration présente saisie, contrôle, justification et information avec des données de test.",
    ctaButton: "Demander une démonstration",
  },
  en: {
    slug: "attendance-absence-parent-updates",
    category: "Attendance guide",
    title: "How should a school manage attendance, absence and parent updates?",
    description: "A clear journey for recording attendance, absence, lateness and justification, then updating families under school policy.",
    directAnswerTitle: "Direct answer",
    directAnswer: "The journey starts by recording the student’s status in the correct lesson or day. Absence or lateness is then reviewed and may receive a justification. Once confirmed, school leaders can follow cases that need action and update the authorised parent under school policy, without opening an uncontrolled personal conversation.",
    updatedLabel: "Last reviewed: 3 August 2026",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    readingTime: "6 minute read",
    sections: [
      { title: "Record the status in the correct context", paragraphs: ["Attendance should be tied to the student, date and relevant lesson or period, with absence, lateness and early departure kept distinct.", "Older changes should remain restricted to authorised users and carry a clear reason."] },
      { title: "Review the justification", paragraphs: ["A justification should remain linked to the original absence together with the review date and decision maker.", "Unjustified or repeated cases remain visible for administrative follow-up."] },
      { title: "Update the family through school communication", paragraphs: ["The update goes only to the parent linked to the student and follows school policy.", "It communicates an approved status without creating an uncontrolled direct chat between teacher and family."] },
    ],
    checklistTitle: "Journey controls",
    checklist: ["Identify date, lesson and student.", "Separate absence, lateness and early departure.", "Link justification to the original status.", "Define who reviews and approves.", "Update only the authorised parent."],
    faqTitle: "Related questions",
    faq: [
      { question: "Does every absence trigger an automatic message?", answer: "That depends on school policy and configuration. Any update should use a correct, approved status and the right recipient." },
      { question: "Does a justification delete the absence?", answer: "No. The absence should remain in the history with its justification and review decision." },
    ],
    relatedTitle: "Related pages",
    relatedLinks: [
      { href: "/roles/teachers", title: "Teacher workspace", description: "Follow-up inside authorised classes and scope." },
      { href: "/roles/parents", title: "Parent workspace", description: "Updates related only to the parent’s children." },
      { href: "/guides/governed-school-communication", title: "Governed school communication", description: "How messages move under institution oversight." },
    ],
    ctaTitle: "See the attendance journey in Raqeem",
    ctaDescription: "The demo presents recording, review, justification and updates using test data and clear roles.",
    ctaButton: "Request a demo",
  },
  es: {
    slug: "attendance-absence-parent-updates",
    category: "Guía de asistencia",
    title: "¿Cómo gestionar asistencia, ausencia e información a las familias?",
    description: "Un recorrido claro para registrar asistencia, ausencia, retraso y justificación, y después informar a la familia según la política del centro.",
    directAnswerTitle: "Respuesta directa",
    directAnswer: "El recorrido comienza registrando el estado del alumno en la clase o jornada correcta. La ausencia o el retraso se revisa y puede recibir una justificación. Una vez confirmado, la dirección sigue los casos que necesitan intervención e informa al familiar autorizado según la política del centro, sin abrir una conversación personal no controlada.",
    updatedLabel: "Última revisión: 3 de agosto de 2026",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    readingTime: "6 minutos de lectura",
    sections: [
      { title: "Registrar el estado en el contexto correcto", paragraphs: ["La asistencia debe vincularse al alumno, la fecha y la clase o periodo, diferenciando ausencia, retraso y salida anticipada.", "Los cambios antiguos deben limitarse a usuarios autorizados y llevar un motivo claro."] },
      { title: "Revisar la justificación", paragraphs: ["La justificación permanece vinculada a la ausencia original con fecha y responsable de revisión.", "Los casos no justificados o repetidos siguen visibles para la dirección."] },
      { title: "Informar a la familia dentro de la comunicación escolar", paragraphs: ["La información llega solo al familiar vinculado al alumno y conforme a la política del centro.", "Comunica un estado aprobado sin crear un chat directo no controlado entre docente y familia."] },
    ],
    checklistTitle: "Controles del recorrido",
    checklist: ["Identificar fecha, clase y alumno.", "Separar ausencia, retraso y salida anticipada.", "Vincular la justificación al estado original.", "Definir quién revisa y aprueba.", "Informar solo al familiar autorizado."],
    faqTitle: "Preguntas relacionadas",
    faq: [
      { question: "¿Cada ausencia envía un mensaje automático?", answer: "Depende de la política y configuración del centro. La información debe basarse en un estado correcto y aprobado." },
      { question: "¿La justificación elimina la ausencia?", answer: "No. La ausencia permanece en el historial con su justificación y decisión de revisión." },
    ],
    relatedTitle: "Páginas relacionadas",
    relatedLinks: [
      { href: "/roles/teachers", title: "Espacio docente", description: "Seguimiento dentro de las clases autorizadas." },
      { href: "/roles/parents", title: "Espacio para familias", description: "Información vinculada únicamente a sus hijos." },
      { href: "/guides/governed-school-communication", title: "Comunicación escolar controlada", description: "Cómo circulan los mensajes bajo supervisión." },
    ],
    ctaTitle: "Ver el recorrido de asistencia en Raqeem",
    ctaDescription: "La demostración presenta registro, revisión, justificación e información con datos de prueba.",
    ctaButton: "Solicitar una demostración",
  },
};

export const rolesPermissionsSensitiveActionsGuide: Record<Locale, CatalogGuideContent> = {
  ar: {
    slug: "roles-permissions-sensitive-actions",
    category: "دليل الصلاحيات",
    title: "من يستطيع فعل ماذا؟ الأدوار والصلاحيات والعمليات الحساسة",
    description: "شرح الفرق بين الدور والقدرة ونطاق البيانات، وكيف تُضبط عمليات المشاهدة والإنشاء والتعديل والحذف والمراجعة والاعتماد.",
    directAnswerTitle: "الإجابة المباشرة",
    directAnswer: "الصلاحية الجيدة لا تعتمد على اسم الدور وحده. يجب تحديد القدرة المطلوبة، ونطاق البيانات التي تشملها، وما إذا كانت العملية عادية أو حساسة. لذلك قد يستطيع المستخدم مشاهدة سجل دون تعديله، أو إعداد محتوى دون اعتماده، أو إنشاء طلب دون حذفه.",
    updatedLabel: "آخر مراجعة: 3 أغسطس 2026",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    readingTime: "قراءة في 6 دقائق",
    sections: [
      { title: "الدور ليس الصلاحية كاملة", paragraphs: ["المدير والنائب والاستقبال والأستاذ وولي الأمر أسماء أدوار، لكن القرارات الفعلية تُبنى على قدرات مثل المشاهدة والإنشاء والتعديل والحذف والمراجعة والاعتماد.", "يمكن أن يختلف نطاق الدور حسب مسؤولية المستخدم داخل المؤسسة."] },
      { title: "حدد نطاق البيانات", paragraphs: ["قد تكون الصلاحية على المؤسسة كلها أو قسم أو تلميذ أو أبناء مرتبطين بالمستخدم فقط.", "النطاق يمنع تحول صلاحية صحيحة في مكانها إلى وصول واسع غير ضروري."] },
      { title: "شدد العمليات الحساسة", paragraphs: ["الحذف والتحويل والاعتماد والتعديلات المالية ونشر المحتوى تحتاج إلى صلاحيات أو مراجعة أو أثر تدقيق يتناسب مع حساسيتها.", "عند تغير مسؤولية الموظف أو مغادرته يجب تحديث الوصول أو إلغاؤه دون تأخير."] },
    ],
    checklistTitle: "مراجعة الصلاحيات",
    checklist: ["تعريف الدور والقدرات منفصلين.", "تحديد نطاق المؤسسة أو القسم أو السجل.", "فصل الإعداد عن المراجعة والاعتماد.", "تقييد الحذف والتعديل المالي والنشر.", "مراجعة الوصول عند تغير المسؤوليات."],
    faqTitle: "أسئلة مرتبطة",
    faq: [
      { question: "هل إخفاء زر يكفي لمنع العملية؟", answer: "لا. يجب أن تُطبق الصلاحية على العملية نفسها، وليس على الواجهة فقط." },
      { question: "هل يملك جميع المديرين الصلاحيات نفسها؟", answer: "ليس بالضرورة. يمكن أن تختلف القدرات والنطاق بحسب المسؤولية المعتمدة داخل المؤسسة." },
    ],
    relatedTitle: "صفحات مرتبطة",
    relatedLinks: [
      { href: "/security", title: "الأمان وحماية البيانات", description: "أقل صلاحية وعزل المؤسسة وقابلية التدقيق." },
      { href: "/guides/school-data-isolation", title: "عزل بيانات المدرسة", description: "الفصل بين المؤسسات ونطاق الرؤية المركزية." },
      { href: "/roles/administration", title: "مساحة الإدارة", description: "المراجعة والاعتماد والتدخل حسب الصلاحية." },
    ],
    ctaTitle: "راجع مصفوفة الصلاحيات في رقيم",
    ctaDescription: "يعرض الفريق الأدوار والقدرات والنطاقات والعمليات الحساسة باستخدام حسابات وبيانات تجريبية.",
    ctaButton: "اطلب عرضًا توضيحيًا",
  },
  fr: {
    slug: "roles-permissions-sensitive-actions",
    category: "Guide des autorisations",
    title: "Qui peut faire quoi ? Rôles, droits et opérations sensibles",
    description: "Comprendre la différence entre rôle, capacité et périmètre, puis contrôler lecture, création, modification, suppression, révision et validation.",
    directAnswerTitle: "Réponse directe",
    directAnswer: "Une autorisation fiable ne dépend pas uniquement du nom du rôle. Elle précise l’action autorisée, le périmètre des données et le niveau de sensibilité. Un utilisateur peut donc consulter sans modifier, préparer sans valider ou créer une demande sans pouvoir la supprimer.",
    updatedLabel: "Dernière révision : 3 août 2026",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    readingTime: "6 minutes de lecture",
    sections: [
      { title: "Le rôle ne suffit pas", paragraphs: ["Direction, accueil, enseignant et parent sont des rôles, mais les décisions réelles reposent sur des capacités comme lire, créer, modifier, supprimer, réviser ou valider.", "Le périmètre peut varier selon la responsabilité réelle de l’utilisateur."] },
      { title: "Définir le périmètre des données", paragraphs: ["Le droit peut couvrir tout l’établissement, une classe, un élève ou uniquement les enfants liés au compte.", "Le périmètre évite qu’un droit légitime devienne un accès trop large."] },
      { title: "Renforcer les opérations sensibles", paragraphs: ["Suppression, conversion, validation, modification financière et publication nécessitent des droits, contrôles ou traces adaptés.", "Les accès doivent être revus dès qu’une responsabilité change ou qu’un utilisateur quitte l’établissement."] },
    ],
    checklistTitle: "Revue des autorisations",
    checklist: ["Séparer rôle et capacités.", "Définir le périmètre des données.", "Séparer préparation, révision et validation.", "Restreindre suppression, finance et publication.", "Revoir les accès lors des changements."],
    faqTitle: "Questions associées",
    faq: [
      { question: "Masquer un bouton suffit-il ?", answer: "Non. Le contrôle doit être appliqué à l’opération elle-même, pas seulement à l’interface." },
      { question: "Tous les directeurs ont-ils les mêmes droits ?", answer: "Pas nécessairement. Les capacités et périmètres peuvent varier selon la responsabilité attribuée." },
    ],
    relatedTitle: "Pages associées",
    relatedLinks: [
      { href: "/security", title: "Sécurité et données", description: "Moindre privilège, isolation et traçabilité." },
      { href: "/guides/school-data-isolation", title: "Isolation des données", description: "Séparation entre établissements et visibilité centrale." },
      { href: "/roles/administration", title: "Espace administration", description: "Révision, validation et intervention selon les droits." },
    ],
    ctaTitle: "Examiner la matrice de droits dans Raqeem",
    ctaDescription: "La démonstration présente rôles, capacités, périmètres et opérations sensibles avec des comptes de test.",
    ctaButton: "Demander une démonstration",
  },
  en: {
    slug: "roles-permissions-sensitive-actions",
    category: "Permissions guide",
    title: "Who can do what? Roles, permissions and sensitive actions",
    description: "Understand role, capability and data scope, then control viewing, creation, editing, deletion, review and approval.",
    directAnswerTitle: "Direct answer",
    directAnswer: "Reliable access control does not depend on the role name alone. It defines the allowed capability, the data scope and whether the action is ordinary or sensitive. A user may view without editing, prepare without approving, or create a request without being allowed to delete it.",
    updatedLabel: "Last reviewed: 3 August 2026",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    readingTime: "6 minute read",
    sections: [
      { title: "A role is not the whole permission", paragraphs: ["Director, reception, teacher and parent are role names, while actual decisions use capabilities such as view, create, edit, delete, review and approve.", "The scope may differ according to the user’s real responsibility."] },
      { title: "Define the data scope", paragraphs: ["A permission may cover the institution, a class, a student or only children linked to the account.", "Scope prevents a valid permission from becoming unnecessarily broad access."] },
      { title: "Strengthen sensitive actions", paragraphs: ["Deletion, conversion, approval, financial changes and publishing require appropriate permissions, review or audit evidence.", "Access should be updated promptly when responsibilities change or a user leaves."] },
    ],
    checklistTitle: "Permission review",
    checklist: ["Keep role and capabilities separate.", "Define institution, class or record scope.", "Separate preparation, review and approval.", "Restrict deletion, finance and publishing.", "Review access when responsibilities change."],
    faqTitle: "Related questions",
    faq: [
      { question: "Is hiding a button enough?", answer: "No. The permission must protect the operation itself, not only the interface." },
      { question: "Do all directors have the same permissions?", answer: "Not necessarily. Capabilities and scope may differ according to assigned responsibility." },
    ],
    relatedTitle: "Related pages",
    relatedLinks: [
      { href: "/security", title: "Security and data protection", description: "Least privilege, isolation and auditability." },
      { href: "/guides/school-data-isolation", title: "School data isolation", description: "Institution separation and central visibility boundaries." },
      { href: "/roles/administration", title: "Administration workspace", description: "Review, approval and intervention under permissions." },
    ],
    ctaTitle: "Review the permission matrix in Raqeem",
    ctaDescription: "The demo presents roles, capabilities, scopes and sensitive actions using test accounts and data.",
    ctaButton: "Request a demo",
  },
  es: {
    slug: "roles-permissions-sensitive-actions",
    category: "Guía de permisos",
    title: "¿Quién puede hacer qué? Roles, permisos y operaciones sensibles",
    description: "Comprender rol, capacidad y ámbito de datos, y controlar lectura, creación, edición, eliminación, revisión y aprobación.",
    directAnswerTitle: "Respuesta directa",
    directAnswer: "Un control fiable no depende solo del nombre del rol. Define la capacidad permitida, el ámbito de los datos y si la acción es normal o sensible. Un usuario puede consultar sin editar, preparar sin aprobar o crear una solicitud sin poder eliminarla.",
    updatedLabel: "Última revisión: 3 de agosto de 2026",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    readingTime: "6 minutos de lectura",
    sections: [
      { title: "El rol no es todo el permiso", paragraphs: ["Dirección, recepción, docente y familia son nombres de rol; las decisiones reales usan capacidades como ver, crear, editar, eliminar, revisar y aprobar.", "El ámbito puede variar según la responsabilidad asignada."] },
      { title: "Definir el ámbito de los datos", paragraphs: ["El permiso puede cubrir la institución, una clase, un alumno o solo los hijos vinculados a la cuenta.", "El ámbito evita que un permiso legítimo se convierta en acceso demasiado amplio."] },
      { title: "Reforzar las operaciones sensibles", paragraphs: ["Eliminación, conversión, aprobación, cambios financieros y publicación necesitan permisos, revisión o trazabilidad adecuados.", "El acceso debe revisarse cuando cambian las responsabilidades o un usuario deja la institución."] },
    ],
    checklistTitle: "Revisión de permisos",
    checklist: ["Separar rol y capacidades.", "Definir el ámbito de institución, clase o registro.", "Separar preparación, revisión y aprobación.", "Restringir eliminación, finanzas y publicación.", "Revisar accesos ante cambios."],
    faqTitle: "Preguntas relacionadas",
    faq: [
      { question: "¿Ocultar un botón es suficiente?", answer: "No. El permiso debe proteger la operación, no solo la interfaz." },
      { question: "¿Todos los directores tienen los mismos permisos?", answer: "No necesariamente. Las capacidades y el ámbito pueden variar según la responsabilidad asignada." },
    ],
    relatedTitle: "Páginas relacionadas",
    relatedLinks: [
      { href: "/security", title: "Seguridad y datos", description: "Mínimo privilegio, aislamiento y trazabilidad." },
      { href: "/guides/school-data-isolation", title: "Aislamiento de datos", description: "Separación de instituciones y límites de visión central." },
      { href: "/roles/administration", title: "Espacio de administración", description: "Revisión, aprobación e intervención según permisos." },
    ],
    ctaTitle: "Revisar la matriz de permisos en Raqeem",
    ctaDescription: "La demostración presenta roles, capacidades, ámbitos y operaciones sensibles con cuentas de prueba.",
    ctaButton: "Solicitar una demostración",
  },
};
