import type { CatalogGuideContent } from "@/content/guide-types";
import type { Locale } from "@/i18n/routing";

export const protectingSchoolDataGuide: Record<Locale, CatalogGuideContent> = {
  ar: {
    slug: "protecting-school-data",
    category: "دليل حماية البيانات",
    title: "كيف تحمي المدرسة بيانات التلاميذ والأسر والموظفين؟",
    description: "مبادئ عملية لتقليل الوصول، عزل المؤسسات، حماية الحسابات، مراجعة الصلاحيات والتعامل الآمن مع الملفات والاختبارات.",
    directAnswerTitle: "الإجابة المباشرة",
    directAnswer: "حماية البيانات لا تعتمد على كلمة آمن وحدها. تبدأ بعزل المؤسسة، ومنح كل مستخدم أقل صلاحية يحتاجها، وإظهار الحقول الحساسة عند وجود حاجة فعلية، ومراجعة الحسابات عند تغير المسؤوليات، واستعمال بيانات تجريبية بدل بيانات الإنتاج في الاختبارات.",
    updatedLabel: "آخر مراجعة: 3 أغسطس 2026",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    readingTime: "قراءة في 6 دقائق",
    sections: [
      { title: "قلل الوصول إلى ما يحتاجه الدور", paragraphs: ["لا يحتاج الأستاذ إلى جميع البيانات المالية، ولا يرى ولي الأمر إلا أبناءه، ولا تُعرض الملفات الحساسة لمستخدم لا تتطلب مهمته ذلك.", "يجب أن تُطبق القيود على العملية والبيانات نفسها، لا على شكل الواجهة فقط."] },
      { title: "احم الحسابات والملفات", paragraphs: ["لا تُشارك كلمات المرور أو رموز التحقق، وتُلغى الحسابات أو الصلاحيات عند مغادرة الموظف أو تغير مسؤوليته.", "تخضع المرفقات لنطاق المؤسسة والدور، ولا تُرفع معلومات لا تحتاجها العملية المدرسية."] },
      { title: "افصل الإنتاج عن الاختبار", paragraphs: ["تُستخدم بيانات خيالية واضحة في التجارب والعروض التوضيحية، ولا تُنسخ بيانات مدرسة حقيقية إلى اختبار عشوائي.", "عند حدوث خطأ أو اشتباه يجب توثيق الواقعة ومراجعة الوصول واتخاذ الإجراء المناسب."] },
    ],
    checklistTitle: "قائمة حماية عملية",
    checklist: ["أقل صلاحية لازمة لكل دور.", "عزل بيانات كل مؤسسة.", "مراجعة الحسابات عند تغير الموظفين.", "تقييد الملفات والحقول الحساسة.", "استعمال بيانات تجريبية في الاختبارات."],
    faqTitle: "أسئلة مرتبطة",
    faq: [
      { question: "هل كل مستخدم داخل المدرسة يرى البيانات نفسها؟", answer: "لا. الوصول يعتمد على الدور والقدرة ونطاق العمل والحاجة الفعلية إلى البيانات." },
      { question: "هل يمكن استعمال بيانات حقيقية في العرض التوضيحي؟", answer: "الأصل استعمال بيانات تجريبية لا تكشف معلومات مدرسة أو أشخاص حقيقيين." },
    ],
    relatedTitle: "صفحات مرتبطة",
    relatedLinks: [
      { href: "/security", title: "الأمان في رقيم", description: "المبادئ والضوابط المنشورة لحماية الحسابات والبيانات." },
      { href: "/guides/school-data-isolation", title: "عزل بيانات المدرسة", description: "الفصل بين المؤسسات ومنع نقل الممارسات." },
      { href: "/guides/roles-permissions-sensitive-actions", title: "الأدوار والعمليات الحساسة", description: "من يستطيع المشاهدة والتعديل والمراجعة والاعتماد." },
    ],
    ctaTitle: "راجع ضوابط حماية البيانات في رقيم",
    ctaDescription: "يعرض الفريق نطاقات الوصول والملفات والبيانات التجريبية دون استعمال بيانات مدرسة حقيقية.",
    ctaButton: "اطلب عرضًا توضيحيًا",
  },
  fr: {
    slug: "protecting-school-data",
    category: "Guide de protection des données",
    title: "Comment protéger les données des élèves, familles et employés ?",
    description: "Des principes pratiques pour limiter l’accès, isoler les établissements, protéger les comptes et séparer production et test.",
    directAnswerTitle: "Réponse directe",
    directAnswer: "La protection ne repose pas sur le mot sécurisé. Elle commence par l’isolation de l’établissement, le moindre privilège, l’affichage des données sensibles uniquement en cas de besoin, la révision des comptes lors des changements et l’usage de données fictives pour les tests.",
    updatedLabel: "Dernière révision : 3 août 2026",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    readingTime: "6 minutes de lecture",
    sections: [
      { title: "Limiter l’accès au besoin réel", paragraphs: ["Un enseignant n’a pas besoin de toutes les données financières et un parent ne voit que ses enfants.", "Les restrictions doivent protéger l’action et les données, pas seulement masquer un élément de l’interface."] },
      { title: "Protéger comptes et fichiers", paragraphs: ["Les mots de passe et codes ne sont pas partagés, et les accès sont retirés lorsqu’un employé change de responsabilité ou quitte l’établissement.", "Les pièces jointes suivent le même périmètre d’accès que les autres données."] },
      { title: "Séparer production et test", paragraphs: ["Les démonstrations et essais utilisent des données fictives clairement identifiées.", "Un incident ou un accès suspect doit être documenté, examiné et traité selon son impact."] },
    ],
    checklistTitle: "Liste de protection",
    checklist: ["Moindre privilège par rôle.", "Isolation des données par établissement.", "Révision des comptes lors des changements.", "Restriction des fichiers et champs sensibles.", "Données fictives pour les tests."],
    faqTitle: "Questions associées",
    faq: [
      { question: "Tous les employés voient-ils les mêmes données ?", answer: "Non. L’accès dépend du rôle, de la capacité, du périmètre et du besoin réel." },
      { question: "Peut-on utiliser des données réelles en démonstration ?", answer: "La règle est d’utiliser des données de test sans informations réelles sur une école ou une personne." },
    ],
    relatedTitle: "Pages associées",
    relatedLinks: [
      { href: "/security", title: "Sécurité chez Raqeem", description: "Les principes publiés pour protéger comptes et données." },
      { href: "/guides/school-data-isolation", title: "Isolation des données", description: "La séparation entre établissements." },
      { href: "/guides/roles-permissions-sensitive-actions", title: "Rôles et opérations sensibles", description: "Lecture, modification, révision et validation." },
    ],
    ctaTitle: "Examiner la protection des données dans Raqeem",
    ctaDescription: "La démonstration présente les périmètres d’accès et les données de test sans exposer une école réelle.",
    ctaButton: "Demander une démonstration",
  },
  en: {
    slug: "protecting-school-data",
    category: "Data protection guide",
    title: "How should a school protect student, family and staff data?",
    description: "Practical principles for limiting access, isolating institutions, protecting accounts and separating production from testing.",
    directAnswerTitle: "Direct answer",
    directAnswer: "Protection is not established by the word secure. It starts with institution isolation, least-privilege access, showing sensitive fields only when needed, reviewing accounts when responsibilities change and using fictional data for testing and demonstrations.",
    updatedLabel: "Last reviewed: 3 August 2026",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    readingTime: "6 minute read",
    sections: [
      { title: "Limit access to the real need", paragraphs: ["Teachers do not need all financial data, and parents see only their linked children.", "Restrictions should protect the operation and data, not merely hide an interface element."] },
      { title: "Protect accounts and files", paragraphs: ["Passwords and verification codes are not shared, and access is removed when staff responsibilities change or employment ends.", "Attachments follow the same institution and role boundaries as other data."] },
      { title: "Separate production and testing", paragraphs: ["Demos and tests use clearly fictional data rather than real school records.", "A suspected incident should be documented, reviewed and handled according to impact."] },
    ],
    checklistTitle: "Protection checklist",
    checklist: ["Least privilege for every role.", "Institution-isolated data.", "Account review when staff change.", "Restricted files and sensitive fields.", "Fictional data in testing."],
    faqTitle: "Related questions",
    faq: [
      { question: "Does every school employee see the same data?", answer: "No. Access depends on role, capability, scope and genuine need." },
      { question: "Can real data be used in a demo?", answer: "The standard approach is test data that does not expose a real school or person." },
    ],
    relatedTitle: "Related pages",
    relatedLinks: [
      { href: "/security", title: "Security at Raqeem", description: "Published principles for protecting accounts and data." },
      { href: "/guides/school-data-isolation", title: "School data isolation", description: "How institution boundaries are maintained." },
      { href: "/guides/roles-permissions-sensitive-actions", title: "Roles and sensitive actions", description: "Viewing, editing, review and approval controls." },
    ],
    ctaTitle: "Review data protection controls in Raqeem",
    ctaDescription: "The demo presents access boundaries and test data without exposing a real school record.",
    ctaButton: "Request a demo",
  },
  es: {
    slug: "protecting-school-data",
    category: "Guía de protección de datos",
    title: "¿Cómo proteger los datos de alumnos, familias y empleados?",
    description: "Principios prácticos para limitar acceso, aislar centros, proteger cuentas y separar producción de pruebas.",
    directAnswerTitle: "Respuesta directa",
    directAnswer: "La protección no se demuestra con la palabra seguro. Comienza con el aislamiento del centro, mínimo privilegio, datos sensibles visibles solo cuando hacen falta, revisión de cuentas ante cambios y uso de datos ficticios para pruebas y demostraciones.",
    updatedLabel: "Última revisión: 3 de agosto de 2026",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    readingTime: "6 minutos de lectura",
    sections: [
      { title: "Limitar el acceso a la necesidad real", paragraphs: ["Un docente no necesita todos los datos financieros y una familia solo ve a sus hijos vinculados.", "Las restricciones deben proteger la operación y los datos, no solo ocultar elementos de la interfaz."] },
      { title: "Proteger cuentas y archivos", paragraphs: ["No se comparten contraseñas ni códigos y se retira el acceso cuando cambia la responsabilidad o termina la relación laboral.", "Los adjuntos siguen los mismos límites de institución y rol."] },
      { title: "Separar producción y pruebas", paragraphs: ["Las demostraciones y pruebas usan datos ficticios claramente identificados.", "Un incidente o acceso sospechoso debe documentarse, revisarse y tratarse según su impacto."] },
    ],
    checklistTitle: "Lista de protección",
    checklist: ["Mínimo privilegio por rol.", "Datos aislados por institución.", "Revisión de cuentas ante cambios.", "Archivos y campos sensibles restringidos.", "Datos ficticios en pruebas."],
    faqTitle: "Preguntas relacionadas",
    faq: [
      { question: "¿Todo el personal ve los mismos datos?", answer: "No. El acceso depende del rol, la capacidad, el ámbito y la necesidad real." },
      { question: "¿Se pueden usar datos reales en una demostración?", answer: "La práctica adecuada es usar datos de prueba sin exponer a un colegio o persona real." },
    ],
    relatedTitle: "Páginas relacionadas",
    relatedLinks: [
      { href: "/security", title: "Seguridad en Raqeem", description: "Principios publicados para proteger cuentas y datos." },
      { href: "/guides/school-data-isolation", title: "Aislamiento de datos", description: "Separación entre instituciones." },
      { href: "/guides/roles-permissions-sensitive-actions", title: "Roles y operaciones sensibles", description: "Controles de lectura, edición, revisión y aprobación." },
    ],
    ctaTitle: "Revisar la protección de datos en Raqeem",
    ctaDescription: "La demostración presenta límites de acceso y datos de prueba sin mostrar registros reales.",
    ctaButton: "Solicitar una demostración",
  },
};

export const timetableConflictManagementGuide: Record<Locale, CatalogGuideContent> = {
  ar: {
    slug: "timetable-conflict-management",
    category: "دليل استعمال الزمن",
    title: "كيف تُعد المدرسة استعمال الزمن وتراجع التعارضات قبل النشر؟",
    description: "مسار من الإعداد والمسودة إلى التحقق من الأستاذ والقسم والقاعة، ثم المراجعة والنشر وفق قرار المؤسسة.",
    directAnswerTitle: "الإجابة المباشرة",
    directAnswer: "يبدأ استعمال الزمن بتحديد السنة والفترات والأيام والموارد، ثم بناء مسودة للحصص. قبل النشر تُراجع التعارضات مثل إسناد الأستاذ أو القسم أو القاعة إلى حصتين في الوقت نفسه، وتُصحح المسودة ويعتمدها المسؤول المخول. لا ينبغي عرض المسودة للتلاميذ والأسر كنسخة نهائية قبل قرار النشر.",
    updatedLabel: "آخر مراجعة: 3 أغسطس 2026",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    readingTime: "قراءة في 6 دقائق",
    sections: [
      { title: "جهز الموارد والقيود", paragraphs: ["يُحدد الأسبوع والفترات والأساتذة والأقسام والقاعات والمواد المتاحة قبل بناء الحصص.", "كلما كانت البيانات الأساسية صحيحة كانت مراجعة التعارضات أوضح."] },
      { title: "ابنِ مسودة قابلة للمراجعة", paragraphs: ["المسودة تسمح بتغيير الحصص دون تقديمها باعتبارها جدولًا نهائيًا.", "تُراجع تعارضات الوقت للأستاذ والقسم والقاعة، إضافة إلى القيود التي تعتمدها المؤسسة."] },
      { title: "اعتمد ثم انشر", paragraphs: ["بعد معالجة التعارضات يراجع المسؤول النسخة ويعتمدها، ثم تُنشر للجهات المصرح لها.", "أي تعديل لاحق يجب أن يوضح النسخة أو الحالة حتى لا تعمل الأطراف على جداول مختلفة دون علمها."] },
    ],
    checklistTitle: "قائمة المراجعة قبل النشر",
    checklist: ["الفترات والأيام مضبوطة.", "كل حصة مرتبطة بقسم ومادة وأستاذ.", "لا تعارض للأستاذ أو القسم أو القاعة.", "المسودة مميزة عن النسخة المنشورة.", "الاعتماد والنشر بيد المستخدم المخول."],
    faqTitle: "أسئلة مرتبطة",
    faq: [
      { question: "هل كشف التعارض يعني توليد الجدول آليًا؟", answer: "لا. يمكن للنظام كشف تعارضات في جدول أُعد يدويًا أو بمساعدة أدوات أخرى دون الادعاء بتوليد كامل تلقائي." },
      { question: "هل يرى التلميذ المسودة؟", answer: "الأصل أن يرى النسخة المنشورة المصرح بها، لا مسودة العمل الداخلي." },
    ],
    relatedTitle: "صفحات مرتبطة",
    relatedLinks: [
      { href: "/timetable", title: "استعمال الزمن في رقيم", description: "الإعداد والبناء والمراجعة والنشر." },
      { href: "/roles/administration", title: "مساحة الإدارة", description: "المراجعة والاعتماد واتخاذ القرار." },
      { href: "/guides/roles-permissions-sensitive-actions", title: "الصلاحيات والعمليات الحساسة", description: "من يراجع ومن يعتمد ومن ينشر." },
    ],
    ctaTitle: "شاهد مراجعة استعمال الزمن في رقيم",
    ctaDescription: "يعرض الفريق إعداد المسودة وكشف التعارضات والمراجعة والنشر باستخدام بيانات تجريبية.",
    ctaButton: "اطلب عرضًا توضيحيًا",
  },
  fr: {
    slug: "timetable-conflict-management",
    category: "Guide d’emploi du temps",
    title: "Comment préparer l’emploi du temps et contrôler les conflits avant publication ?",
    description: "Un parcours de la configuration et du brouillon au contrôle enseignant, classe et salle, puis à la validation et publication.",
    directAnswerTitle: "Réponse directe",
    directAnswer: "L’emploi du temps commence par les périodes, jours et ressources, puis une version brouillon. Avant publication, l’établissement contrôle qu’un enseignant, une classe ou une salle n’est pas affecté à deux séances au même moment. Le responsable corrige, valide puis publie la version autorisée.",
    updatedLabel: "Dernière révision : 3 août 2026",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    readingTime: "6 minutes de lecture",
    sections: [
      { title: "Préparer ressources et contraintes", paragraphs: ["Les périodes, enseignants, classes, salles et matières sont définis avant la construction.", "Des données de base correctes rendent les conflits plus faciles à comprendre."] },
      { title: "Construire un brouillon révisable", paragraphs: ["Le brouillon permet de déplacer les séances sans les présenter comme version finale.", "Les conflits de temps sont vérifiés pour enseignant, classe et salle, avec les règles propres à l’établissement."] },
      { title: "Valider puis publier", paragraphs: ["Après correction, le responsable autorisé valide et publie la version destinée aux utilisateurs.", "Une modification ultérieure doit rester identifiable afin d’éviter plusieurs versions contradictoires."] },
    ],
    checklistTitle: "Contrôle avant publication",
    checklist: ["Périodes et jours configurés.", "Chaque séance liée à classe, matière et enseignant.", "Aucun conflit enseignant, classe ou salle.", "Brouillon distinct de la version publiée.", "Validation et publication par le rôle autorisé."],
    faqTitle: "Questions associées",
    faq: [
      { question: "Détecter un conflit signifie-t-il générer automatiquement l’emploi du temps ?", answer: "Non. Le contrôle peut s’appliquer à un planning construit manuellement sans promettre une génération automatique complète." },
      { question: "L’élève voit-il le brouillon ?", answer: "La règle est d’afficher la version publiée et autorisée, pas le brouillon interne." },
    ],
    relatedTitle: "Pages associées",
    relatedLinks: [
      { href: "/timetable", title: "Emploi du temps dans Raqeem", description: "Configuration, construction, contrôle et publication." },
      { href: "/roles/administration", title: "Espace administration", description: "Révision, validation et décision." },
      { href: "/guides/roles-permissions-sensitive-actions", title: "Droits et opérations sensibles", description: "Qui révise, valide et publie." },
    ],
    ctaTitle: "Voir le contrôle d’emploi du temps dans Raqeem",
    ctaDescription: "La démonstration présente brouillon, conflits, validation et publication avec des données de test.",
    ctaButton: "Demander une démonstration",
  },
  en: {
    slug: "timetable-conflict-management",
    category: "Timetable guide",
    title: "How should a school build a timetable and review conflicts before publishing?",
    description: "A journey from setup and draft to teacher, class and room conflict checks, then review and publication.",
    directAnswerTitle: "Direct answer",
    directAnswer: "Timetable work starts with periods, days and resources, then a draft schedule. Before publication, the school checks that a teacher, class or room is not assigned to two lessons at the same time. An authorised leader corrects, approves and publishes the version intended for users.",
    updatedLabel: "Last reviewed: 3 August 2026",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    readingTime: "6 minute read",
    sections: [
      { title: "Prepare resources and constraints", paragraphs: ["Periods, teachers, classes, rooms and subjects are defined before lessons are arranged.", "Accurate foundation data makes conflict review clearer."] },
      { title: "Build a reviewable draft", paragraphs: ["A draft allows lessons to move without presenting the schedule as final.", "Time conflicts are checked for teacher, class and room together with school-specific constraints."] },
      { title: "Approve and publish", paragraphs: ["After conflicts are handled, the authorised leader approves and publishes the user-facing version.", "Later changes should remain identifiable so different groups do not unknowingly use conflicting versions."] },
    ],
    checklistTitle: "Pre-publication checklist",
    checklist: ["Periods and days configured.", "Every lesson linked to class, subject and teacher.", "No teacher, class or room conflict.", "Draft distinct from published version.", "Approval and publication restricted to authorised roles."],
    faqTitle: "Related questions",
    faq: [
      { question: "Does conflict detection mean automatic timetable generation?", answer: "No. Conflict checks may support a manually built timetable without claiming full automatic generation." },
      { question: "Do students see the draft?", answer: "The normal approach is to show the approved published version, not the internal draft." },
    ],
    relatedTitle: "Related pages",
    relatedLinks: [
      { href: "/timetable", title: "Timetables in Raqeem", description: "Setup, build, review and publication." },
      { href: "/roles/administration", title: "Administration workspace", description: "Review, approval and decision-making." },
      { href: "/guides/roles-permissions-sensitive-actions", title: "Permissions and sensitive actions", description: "Who reviews, approves and publishes." },
    ],
    ctaTitle: "See timetable review in Raqeem",
    ctaDescription: "The demo presents draft building, conflict checks, approval and publication using test data.",
    ctaButton: "Request a demo",
  },
  es: {
    slug: "timetable-conflict-management",
    category: "Guía de horarios",
    title: "¿Cómo preparar el horario y revisar conflictos antes de publicarlo?",
    description: "Un recorrido desde configuración y borrador hasta control de docente, clase y aula, revisión y publicación.",
    directAnswerTitle: "Respuesta directa",
    directAnswer: "El horario comienza con periodos, días y recursos, y después se construye un borrador. Antes de publicarlo, el centro comprueba que un docente, clase o aula no tenga dos sesiones al mismo tiempo. Una persona autorizada corrige, aprueba y publica la versión destinada a usuarios.",
    updatedLabel: "Última revisión: 3 de agosto de 2026",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    readingTime: "6 minutos de lectura",
    sections: [
      { title: "Preparar recursos y restricciones", paragraphs: ["Se definen periodos, docentes, clases, aulas y materias antes de organizar sesiones.", "Datos básicos correctos facilitan la revisión de conflictos."] },
      { title: "Construir un borrador revisable", paragraphs: ["El borrador permite mover sesiones sin presentarlas como versión final.", "Se revisan conflictos de tiempo para docente, clase y aula, además de las reglas del centro."] },
      { title: "Aprobar y publicar", paragraphs: ["Después de corregir conflictos, la persona autorizada aprueba y publica la versión visible.", "Los cambios posteriores deben quedar identificados para evitar versiones contradictorias."] },
    ],
    checklistTitle: "Control antes de publicar",
    checklist: ["Periodos y días configurados.", "Cada sesión vinculada a clase, materia y docente.", "Sin conflictos de docente, clase o aula.", "Borrador distinto de versión publicada.", "Aprobación y publicación restringidas."],
    faqTitle: "Preguntas relacionadas",
    faq: [
      { question: "¿Detectar conflictos significa generar el horario automáticamente?", answer: "No. El control puede aplicarse a un horario construido manualmente sin prometer generación automática completa." },
      { question: "¿El alumno ve el borrador?", answer: "La práctica normal es mostrar la versión aprobada y publicada, no el borrador interno." },
    ],
    relatedTitle: "Páginas relacionadas",
    relatedLinks: [
      { href: "/timetable", title: "Horarios en Raqeem", description: "Configuración, construcción, revisión y publicación." },
      { href: "/roles/administration", title: "Espacio de administración", description: "Revisión, aprobación y decisión." },
      { href: "/guides/roles-permissions-sensitive-actions", title: "Permisos y operaciones sensibles", description: "Quién revisa, aprueba y publica." },
    ],
    ctaTitle: "Ver la revisión de horarios en Raqeem",
    ctaDescription: "La demostración presenta borrador, conflictos, aprobación y publicación con datos de prueba.",
    ctaButton: "Solicitar una demostración",
  },
};

export const migratingFromExcelGuide: Record<Locale, CatalogGuideContent> = {
  ar: {
    slug: "migrating-from-excel",
    category: "دليل الانتقال",
    title: "كيف تنتقل المدرسة من Excel أو نظام قديم إلى رقيم؟",
    description: "خطة عملية لجرد البيانات وتنظيفها وتجربة الاستيراد ومطابقة النتائج ثم الإطلاق التدريجي دون تعطيل العمل.",
    directAnswerTitle: "الإجابة المباشرة",
    directAnswer: "الانتقال الآمن لا يبدأ برفع كل الملفات دفعة واحدة. تبدأ المدرسة بجرد المصادر، وتحديد البيانات التي ما زالت صالحة، وتنظيف التكرار والصيغ، ثم تنفيذ استيراد تجريبي على عينة ومطابقة الأعداد والأرصدة والعلاقات. بعد قبول النتيجة يُحدد موعد القطع والإطلاق مع نسخة مرجعية وخطة لمعالجة الاستثناءات.",
    updatedLabel: "آخر مراجعة: 3 أغسطس 2026",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    readingTime: "قراءة في 7 دقائق",
    sections: [
      { title: "اجرد المصادر وحدد النطاق", paragraphs: ["تُجمع ملفات التلاميذ والأسر والتمدرس والمالية والموظفين مع معرفة مالك كل ملف وتاريخ تحديثه.", "لا تُنقل الأعمدة القديمة لمجرد وجودها؛ يُحدد ما يحتاجه التشغيل الحالي وما يجب أرشفته خارج الاستيراد."] },
      { title: "نظف وجرّب على عينة", paragraphs: ["تُوحد التواريخ والأسماء والمعرفات وتُراجع السجلات المكررة والعلاقات الناقصة.", "يُنفذ استيراد تجريبي محدود ثم تُقارن النتائج بالمصدر قبل السماح بالانتقال الكامل."] },
      { title: "طابق ثم أطلق تدريجيًا", paragraphs: ["تُطابق أعداد التلاميذ والأسر والتمدرسات والمبالغ المهمة، وتُسجل الاستثناءات التي تحتاج معالجة يدوية.", "يُحدد وقت توقف التعديل في المصدر القديم، وموعد الانتقال، ومسؤولية التحقق بعد الإطلاق."] },
    ],
    checklistTitle: "قائمة الانتقال",
    checklist: ["جرد الملفات وملاكها وتواريخها.", "تحديد النطاق والحقول المطلوبة.", "تنظيف التكرار والصيغ والعلاقات.", "استيراد تجريبي ومطابقة النتائج.", "خطة قطع وإطلاق ومعالجة الاستثناءات."],
    faqTitle: "أسئلة مرتبطة",
    faq: [
      { question: "هل يمكن استيراد أي ملف Excel كما هو؟", answer: "لا. يجب أولًا مطابقة الأعمدة والصيغ والعلاقات مع نموذج البيانات المطلوب وتحديد ما يحتاج تنظيفًا أو معالجة يدوية." },
      { question: "هل نحذف النظام القديم فورًا؟", answer: "لا. تُحفظ نسخة مرجعية وفق سياسة المؤسسة إلى أن تنتهي المطابقة ويُعتمد الانتقال." },
    ],
    relatedTitle: "صفحات مرتبطة",
    relatedLinks: [
      { href: "/guides/choosing-school-management-system", title: "اختيار نظام إدارة مدرسية", description: "معايير الترحيل والدعم قبل التعاقد." },
      { href: "/guides/admission-to-student-record", title: "طلب التسجيل إلى ملف التلميذ", description: "النموذج التشغيلي الذي تستقر فيه البيانات الجديدة." },
      { href: "/demo", title: "طلب عرض توضيحي", description: "مناقشة شكل البيانات ومسار الانتقال المتوقع." },
    ],
    ctaTitle: "ناقش خطة الانتقال إلى رقيم",
    ctaDescription: "يعرض الفريق نموذج البيانات والخطوات التي تحتاج تحققًا قبل أي استيراد فعلي.",
    ctaButton: "اطلب عرضًا توضيحيًا",
  },
  fr: {
    slug: "migrating-from-excel",
    category: "Guide de migration",
    title: "Comment passer d’Excel ou d’un ancien logiciel à Raqeem ?",
    description: "Une méthode pour inventorier, nettoyer, tester l’import, rapprocher les résultats et lancer progressivement sans interrompre l’école.",
    directAnswerTitle: "Réponse directe",
    directAnswer: "Une migration sûre ne consiste pas à déposer tous les fichiers en une fois. L’école inventorie les sources, choisit les données encore utiles, nettoie doublons et formats, teste un échantillon et rapproche volumes, soldes et relations. Après validation, elle planifie la coupure, le lancement et le traitement des exceptions.",
    updatedLabel: "Dernière révision : 3 août 2026",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    readingTime: "7 minutes de lecture",
    sections: [
      { title: "Inventorier les sources et le périmètre", paragraphs: ["Les fichiers élèves, familles, scolarité, finance et personnel sont recensés avec leur propriétaire et leur date.", "Un ancien champ n’est pas importé simplement parce qu’il existe ; sa valeur opérationnelle doit être confirmée."] },
      { title: "Nettoyer et tester un échantillon", paragraphs: ["Dates, noms et identifiants sont harmonisés, puis doublons et relations manquantes sont examinés.", "Un import limité est contrôlé avant d’autoriser le volume complet."] },
      { title: "Rapprocher puis lancer progressivement", paragraphs: ["Les volumes importants et soldes sont comparés, tandis que les exceptions sont documentées.", "L’établissement fixe la fin des modifications dans l’ancien outil, la date de bascule et les responsables de contrôle."] },
    ],
    checklistTitle: "Liste de migration",
    checklist: ["Inventaire des fichiers et responsables.", "Périmètre et champs nécessaires.", "Nettoyage des formats, doublons et relations.", "Import pilote et rapprochement.", "Plan de bascule et gestion des exceptions."],
    faqTitle: "Questions associées",
    faq: [
      { question: "Peut-on importer n’importe quel fichier Excel tel quel ?", answer: "Non. Les colonnes, formats et relations doivent être rapprochés du modèle attendu et les anomalies traitées." },
      { question: "Faut-il supprimer l’ancien système immédiatement ?", answer: "Non. Une copie de référence est conservée selon la politique de l’établissement jusqu’à validation complète." },
    ],
    relatedTitle: "Pages associées",
    relatedLinks: [
      { href: "/guides/choosing-school-management-system", title: "Choisir un système scolaire", description: "Migration et accompagnement avant contrat." },
      { href: "/guides/admission-to-student-record", title: "De la demande au dossier élève", description: "Le modèle opérationnel qui reçoit les nouvelles données." },
      { href: "/demo", title: "Demander une démonstration", description: "Examiner les données et le parcours de migration." },
    ],
    ctaTitle: "Discuter du passage à Raqeem",
    ctaDescription: "L’équipe présente le modèle de données et les contrôles nécessaires avant tout import réel.",
    ctaButton: "Demander une démonstration",
  },
  en: {
    slug: "migrating-from-excel",
    category: "Migration guide",
    title: "How should a school move from Excel or a legacy system to Raqeem?",
    description: "A practical plan to inventory, clean, test imports, reconcile results and launch gradually without disrupting school work.",
    directAnswerTitle: "Direct answer",
    directAnswer: "Safe migration does not start by uploading every file at once. The school inventories sources, selects data that remains useful, cleans duplicates and formats, tests a sample and reconciles counts, balances and relationships. After approval, it plans the cutover, launch and exception handling.",
    updatedLabel: "Last reviewed: 3 August 2026",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    readingTime: "7 minute read",
    sections: [
      { title: "Inventory sources and scope", paragraphs: ["Student, family, enrolment, finance and staff files are listed with their owner and date.", "An old column is not imported simply because it exists; its current operational value must be confirmed."] },
      { title: "Clean and test a sample", paragraphs: ["Dates, names and identifiers are standardised, while duplicates and missing relationships are reviewed.", "A limited pilot import is checked before the full volume is accepted."] },
      { title: "Reconcile and launch gradually", paragraphs: ["Important counts and balances are compared, and exceptions are documented for manual treatment.", "The school defines the final edit time in the old source, the cutover date and post-launch verification owners."] },
    ],
    checklistTitle: "Migration checklist",
    checklist: ["Inventory files and owners.", "Define scope and required fields.", "Clean formats, duplicates and relationships.", "Run a pilot import and reconcile.", "Plan cutover, launch and exceptions."],
    faqTitle: "Related questions",
    faq: [
      { question: "Can any Excel file be imported as it is?", answer: "No. Columns, formats and relationships must match the expected data model, with anomalies cleaned or handled manually." },
      { question: "Should the old system be deleted immediately?", answer: "No. A reference copy is retained under school policy until reconciliation and acceptance are complete." },
    ],
    relatedTitle: "Related pages",
    relatedLinks: [
      { href: "/guides/choosing-school-management-system", title: "Choosing a school system", description: "Migration and support questions before contracting." },
      { href: "/guides/admission-to-student-record", title: "From application to student record", description: "The operational model receiving new data." },
      { href: "/demo", title: "Request a demo", description: "Review the data shape and expected migration journey." },
    ],
    ctaTitle: "Discuss moving to Raqeem",
    ctaDescription: "The team presents the data model and checks required before any real import.",
    ctaButton: "Request a demo",
  },
  es: {
    slug: "migrating-from-excel",
    category: "Guía de migración",
    title: "¿Cómo pasar de Excel o un sistema antiguo a Raqeem?",
    description: "Un plan para inventariar, limpiar, probar la importación, conciliar resultados y lanzar gradualmente sin interrumpir el colegio.",
    directAnswerTitle: "Respuesta directa",
    directAnswer: "Una migración segura no empieza subiendo todos los archivos a la vez. El colegio inventaría las fuentes, selecciona datos todavía útiles, limpia duplicados y formatos, prueba una muestra y concilia cantidades, saldos y relaciones. Tras la aprobación, planifica el cambio, lanzamiento y tratamiento de excepciones.",
    updatedLabel: "Última revisión: 3 de agosto de 2026",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    readingTime: "7 minutos de lectura",
    sections: [
      { title: "Inventariar fuentes y alcance", paragraphs: ["Se registran archivos de alumnos, familias, escolaridad, finanzas y personal con responsable y fecha.", "Un campo antiguo no se importa solo porque existe; debe confirmarse su utilidad actual."] },
      { title: "Limpiar y probar una muestra", paragraphs: ["Se normalizan fechas, nombres e identificadores, y se revisan duplicados y relaciones incompletas.", "Una importación piloto limitada se verifica antes del volumen completo."] },
      { title: "Conciliar y lanzar gradualmente", paragraphs: ["Se comparan cantidades y saldos importantes, y se documentan excepciones para tratamiento manual.", "El colegio fija el último momento de edición, la fecha de cambio y los responsables de verificación posterior."] },
    ],
    checklistTitle: "Lista de migración",
    checklist: ["Inventario de archivos y responsables.", "Alcance y campos necesarios.", "Limpieza de formatos, duplicados y relaciones.", "Importación piloto y conciliación.", "Plan de cambio y excepciones."],
    faqTitle: "Preguntas relacionadas",
    faq: [
      { question: "¿Se puede importar cualquier archivo Excel tal como está?", answer: "No. Columnas, formatos y relaciones deben corresponder al modelo esperado y las anomalías deben tratarse." },
      { question: "¿Hay que borrar el sistema antiguo inmediatamente?", answer: "No. Se conserva una copia de referencia según la política del colegio hasta completar la conciliación." },
    ],
    relatedTitle: "Páginas relacionadas",
    relatedLinks: [
      { href: "/guides/choosing-school-management-system", title: "Elegir un sistema escolar", description: "Migración y soporte antes de contratar." },
      { href: "/guides/admission-to-student-record", title: "De la solicitud al expediente", description: "El modelo operativo que recibe los datos." },
      { href: "/demo", title: "Solicitar una demostración", description: "Revisar los datos y el recorrido esperado." },
    ],
    ctaTitle: "Hablar del paso a Raqeem",
    ctaDescription: "El equipo presenta el modelo de datos y los controles necesarios antes de una importación real.",
    ctaButton: "Solicitar una demostración",
  },
};

export const multiBranchSchoolManagementGuide: Record<Locale, CatalogGuideContent> = {
  ar: {
    slug: "multi-branch-school-management",
    category: "دليل المجموعات المدرسية",
    title: "كيف تدير مجموعة مدرسية عدة فروع مع الحفاظ على استقلال كل مؤسسة؟",
    description: "توازن بين رؤية مركزية مخولة ونطاق مستقل لكل فرع، دون فتح البيانات أو نقل ممارسات مدرسة إلى أخرى.",
    directAnswerTitle: "الإجابة المباشرة",
    directAnswer: "إدارة الفروع تعني أن الجهة المالكة تستطيع منح مستخدمين مركزيين رؤية محددة على المؤسسات المرتبطة بها إداريًا، مع بقاء كل فرع داخل نطاقه وصلاحياته. لا تعني المقارنة بين مدارس مستقلة، ولا مشاركة البيانات أو الإعدادات أو أساليب العمل بين المؤسسات.",
    updatedLabel: "آخر مراجعة: 3 أغسطس 2026",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    readingTime: "قراءة في 6 دقائق",
    sections: [
      { title: "ثبت العلاقة الإدارية قبل الرؤية المركزية", paragraphs: ["لا تُمنح الرؤية المركزية إلا داخل مجموعة ذات ملكية أو إدارة فعلية وصلاحيات موثقة.", "يُحدد المستخدم المركزي والمؤسسات التي يشملها نطاقه والعمليات التي يستطيع تنفيذها."] },
      { title: "حافظ على استقلال كل فرع", paragraphs: ["تبقى بيانات التلاميذ والأسر والموظفين والمالية مرتبطة بالفرع الصحيح، وتُطبق الصلاحيات داخله.", "لا يستطيع مدير فرع الوصول إلى فرع آخر لمجرد وجودهما في المنصة نفسها."] },
      { title: "لا تنقل الممارسات بين المدارس", paragraphs: ["الرؤية الإدارية المصرح بها لا تتحول إلى مقارنة علنية أو توصيات مأخوذة من طريقة عمل مدرسة أخرى.", "لا تُشارك التجارب أو الإعدادات أو المؤشرات بين مؤسسات مستقلة، حتى بصيغة مجهولة أو مجمعة بقصد نقل الممارسة."] },
    ],
    checklistTitle: "ضوابط إدارة الفروع",
    checklist: ["إثبات العلاقة الإدارية للمجموعة.", "تحديد المستخدمين المركزيين ونطاقهم.", "ربط كل سجل بالفرع الصحيح.", "منع الوصول بين الفروع دون صلاحية.", "منع مشاركة الممارسات والمقارنات بين المدارس."],
    faqTitle: "أسئلة مرتبطة",
    faq: [
      { question: "هل يستطيع مدير المجموعة رؤية كل الفروع؟", answer: "فقط إذا كانت العلاقة الإدارية مثبتة ومُنح صلاحية مركزية محددة على تلك الفروع." },
      { question: "هل تستفيد مدرسة من بيانات فرع آخر؟", answer: "لا. لا تُنقل بيانات أو ممارسات فرع إلى مؤسسة أخرى خارج النطاق الإداري المصرح به." },
    ],
    relatedTitle: "صفحات مرتبطة",
    relatedLinks: [
      { href: "/guides/school-data-isolation", title: "عزل بيانات المدرسة", description: "الفصل بين المؤسسات وحدود الرؤية المركزية." },
      { href: "/guides/roles-permissions-sensitive-actions", title: "الأدوار والصلاحيات", description: "تحديد قدرات المدير المركزي ومدير الفرع." },
      { href: "/institutions/schools", title: "رقيم للمدارس", description: "تشغيل المدارس الخاصة داخل نطاق واضح." },
    ],
    ctaTitle: "شاهد إدارة الفروع في رقيم",
    ctaDescription: "يعرض الفريق نطاق المجموعة والفرع والصلاحيات المركزية باستخدام مؤسسات وبيانات تجريبية.",
    ctaButton: "اطلب عرضًا توضيحيًا",
  },
  fr: {
    slug: "multi-branch-school-management",
    category: "Guide des groupes scolaires",
    title: "Comment gérer plusieurs sites tout en préservant l’autonomie de chaque établissement ?",
    description: "Un équilibre entre visibilité centrale autorisée et périmètre indépendant de chaque site, sans transfert de données ou de pratiques.",
    directAnswerTitle: "Réponse directe",
    directAnswer: "La gestion multi-sites permet à une organisation propriétaire d’accorder une visibilité centrale limitée sur les établissements réellement liés, tout en conservant le périmètre et les droits propres à chaque site. Elle ne signifie ni comparaison entre écoles indépendantes, ni partage de données, réglages ou méthodes.",
    updatedLabel: "Dernière révision : 3 août 2026",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    readingTime: "6 minutes de lecture",
    sections: [
      { title: "Établir le lien administratif", paragraphs: ["La visibilité centrale n’est accordée que dans un groupe avec propriété ou gestion réelle et droits documentés.", "Le périmètre de chaque utilisateur central et les opérations autorisées sont définis explicitement."] },
      { title: "Préserver l’autonomie de chaque site", paragraphs: ["Les données élèves, familles, personnel et finance restent rattachées au bon établissement.", "Un directeur de site n’accède pas à un autre site uniquement parce qu’ils utilisent la même plateforme."] },
      { title: "Ne pas transférer les pratiques", paragraphs: ["La vue administrative autorisée ne devient pas une comparaison publique ni une recommandation tirée des méthodes d’une autre école.", "Les pratiques ou indicateurs ne sont pas partagés entre établissements indépendants, même sous forme anonymisée dans le but de transférer une méthode."] },
    ],
    checklistTitle: "Contrôles multi-sites",
    checklist: ["Relation administrative établie.", "Utilisateurs centraux et périmètre définis.", "Chaque donnée liée au bon site.", "Accès inter-sites interdit sans droit.", "Aucun partage de pratiques entre écoles."],
    faqTitle: "Questions associées",
    faq: [
      { question: "La direction du groupe voit-elle tous les sites ?", answer: "Seulement lorsque le lien administratif est établi et qu’un droit central précis a été accordé." },
      { question: "Une école profite-t-elle des données d’un autre site ?", answer: "Non. Les données et méthodes ne sont pas transférées hors du périmètre administratif autorisé." },
    ],
    relatedTitle: "Pages associées",
    relatedLinks: [
      { href: "/guides/school-data-isolation", title: "Isolation des données", description: "Séparation entre établissements et limites de visibilité." },
      { href: "/guides/roles-permissions-sensitive-actions", title: "Rôles et droits", description: "Capacités de la direction centrale et locale." },
      { href: "/institutions/schools", title: "Raqeem pour les écoles", description: "Exploitation des écoles privées dans un périmètre clair." },
    ],
    ctaTitle: "Voir la gestion multi-sites dans Raqeem",
    ctaDescription: "La démonstration présente groupe, site et droits centraux avec des établissements et données de test.",
    ctaButton: "Demander une démonstration",
  },
  en: {
    slug: "multi-branch-school-management",
    category: "School group guide",
    title: "How can a school group manage several branches while preserving each institution’s autonomy?",
    description: "Balance authorised central visibility with an independent scope for every branch, without transferring data or school practices.",
    directAnswerTitle: "Direct answer",
    directAnswer: "Multi-branch management lets the owning organisation grant limited central visibility across institutions that are genuinely connected, while each branch keeps its own scope and permissions. It does not mean comparing independent schools or sharing their data, settings or operating methods.",
    updatedLabel: "Last reviewed: 3 August 2026",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    readingTime: "6 minute read",
    sections: [
      { title: "Establish the administrative relationship", paragraphs: ["Central visibility is granted only inside a group with real ownership or management and documented permissions.", "Each central user’s institutions, data scope and allowed actions are defined explicitly."] },
      { title: "Preserve branch autonomy", paragraphs: ["Student, family, staff and finance data remain tied to the correct branch and its internal permissions.", "A branch director does not gain access to another branch merely because both use the platform."] },
      { title: "Do not transfer school practices", paragraphs: ["Authorised management visibility does not become public comparison or recommendations copied from another school’s methods.", "Practices and indicators are not shared between independent institutions, even in anonymised or aggregated form for practice transfer."] },
    ],
    checklistTitle: "Multi-branch controls",
    checklist: ["Established administrative relationship.", "Defined central users and scope.", "Every record tied to the correct branch.", "No cross-branch access without permission.", "No sharing of school practices or comparisons."],
    faqTitle: "Related questions",
    faq: [
      { question: "Can the school group director see every branch?", answer: "Only when the administrative relationship is established and explicit central permission covers those branches." },
      { question: "Does one school benefit from another branch’s data?", answer: "No. Data and operating methods are not transferred outside the authorised administrative scope." },
    ],
    relatedTitle: "Related pages",
    relatedLinks: [
      { href: "/guides/school-data-isolation", title: "School data isolation", description: "Institution separation and central visibility boundaries." },
      { href: "/guides/roles-permissions-sensitive-actions", title: "Roles and permissions", description: "Central and branch management capabilities." },
      { href: "/institutions/schools", title: "Raqeem for schools", description: "Private school operations within a clear scope." },
    ],
    ctaTitle: "See multi-branch management in Raqeem",
    ctaDescription: "The demo presents group, branch and central permissions using fictional institutions and test data.",
    ctaButton: "Request a demo",
  },
  es: {
    slug: "multi-branch-school-management",
    category: "Guía de grupos escolares",
    title: "¿Cómo gestionar varias sedes preservando la autonomía de cada institución?",
    description: "Equilibrar visión central autorizada y ámbito independiente de cada sede, sin transferir datos ni prácticas escolares.",
    directAnswerTitle: "Respuesta directa",
    directAnswer: "La gestión de varias sedes permite a la organización propietaria conceder una visión central limitada sobre instituciones realmente vinculadas, mientras cada sede conserva su ámbito y permisos. No significa comparar colegios independientes ni compartir datos, ajustes o métodos de trabajo.",
    updatedLabel: "Última revisión: 3 de agosto de 2026",
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    readingTime: "6 minutos de lectura",
    sections: [
      { title: "Establecer la relación administrativa", paragraphs: ["La visión central solo se concede dentro de un grupo con propiedad o gestión real y permisos documentados.", "Se definen las instituciones, el ámbito de datos y las acciones de cada usuario central."] },
      { title: "Preservar la autonomía de cada sede", paragraphs: ["Los datos de alumnos, familias, personal y finanzas permanecen vinculados a la sede correcta.", "Un director de sede no accede a otra únicamente porque ambas utilicen la plataforma."] },
      { title: "No transferir prácticas escolares", paragraphs: ["La visión administrativa autorizada no se convierte en comparación pública ni recomendaciones copiadas de otro colegio.", "No se comparten prácticas o indicadores entre instituciones independientes, incluso de forma anónima o agregada para transferir métodos."] },
    ],
    checklistTitle: "Controles de varias sedes",
    checklist: ["Relación administrativa establecida.", "Usuarios centrales y ámbito definidos.", "Cada registro vinculado a la sede correcta.", "Sin acceso entre sedes sin permiso.", "Sin compartir prácticas ni comparar colegios."],
    faqTitle: "Preguntas relacionadas",
    faq: [
      { question: "¿La dirección del grupo puede ver todas las sedes?", answer: "Solo cuando existe relación administrativa y un permiso central explícito sobre esas sedes." },
      { question: "¿Un colegio aprovecha los datos de otra sede?", answer: "No. Los datos y métodos no se transfieren fuera del ámbito administrativo autorizado." },
    ],
    relatedTitle: "Páginas relacionadas",
    relatedLinks: [
      { href: "/guides/school-data-isolation", title: "Aislamiento de datos", description: "Separación de instituciones y límites de visión central." },
      { href: "/guides/roles-permissions-sensitive-actions", title: "Roles y permisos", description: "Capacidades de dirección central y local." },
      { href: "/institutions/schools", title: "Raqeem para colegios", description: "Operaciones de colegios privados con ámbito claro." },
    ],
    ctaTitle: "Ver la gestión de sedes en Raqeem",
    ctaDescription: "La demostración presenta grupo, sede y permisos centrales con instituciones ficticias y datos de prueba.",
    ctaButton: "Solicitar una demostración",
  },
};
