import type { CatalogGuideContent } from "@/content/guide-types";
import type { Locale } from "@/i18n/routing";

const common = {
  publishedAt: "2026-08-13",
  updatedAt: "2026-08-13",
};

export const privateSchoolManagementMoroccoGuide: Record<Locale, CatalogGuideContent> = {
  ar: {
    slug: "private-school-management-morocco", category: "دليل إدارة المدارس في المغرب", title: "برنامج إدارة المدارس الخاصة في المغرب: ماذا يجب أن يوفر؟", description: "دليل عملي لاختيار برنامج إدارة مدرسة خاصة في المغرب: التسجيل والتمدرس والمالية والحضور والتواصل وتهيئة البيانات المرتبطة بمسار.", directAnswerTitle: "الإجابة المباشرة", directAnswer: "برنامج إدارة المدارس الخاصة في المغرب يجب أن يربط التلاميذ والأسر والتسجيل والتمدرس والمالية والحضور واستعمال الزمن والتواصل في نظام واحد بصلاحيات واضحة وعزل لبيانات المؤسسة. رقيم يدير هذه العمليات ويمكنه إعداد ملفات مهيأة وقابلة للرفع على مسار وفق التصدير المدعوم، بعد مراجعتها من المستخدم المخول، دون ادعاء مزامنة مباشرة.", ...common, updatedLabel: "آخر مراجعة: 13 أغسطس 2026", readingTime: "قراءة في 6 دقائق",
    sections: [{ title: "ما الذي تحتاجه المدرسة الخاصة؟", paragraphs: ["الأهم هو سجل موحد للتلميذ والأسرة يربط التسجيل بالتمدرس والأداء والحضور والمتابعة.", "ينبغي أن تعمل الصلاحيات حسب الدور وأن تبقى بيانات المؤسسة معزولة وقابلة للتتبع."] }, { title: "العمليات التي يجمعها رقيم", paragraphs: ["يربط رقيم التسجيل وملفات التلاميذ والأسر والسنة الدراسية والأقسام والمالية والحضور واستعمال الزمن والتواصل المدرسي.", "الهدف هو تقليل إعادة إدخال البيانات والعمل على مرجع موحد."], points: ["التسجيل وملف التلميذ والأسرة.", "التمدرس والأقسام.", "الواجبات والتحصيل والوصولات.", "الحضور واستعمال الزمن والتواصل."] }, { title: "ماذا عن مسار؟", paragraphs: ["يبقى مسار نظامًا خارجيًا. يستطيع رقيم إعداد ملفات قابلة للرفع وفق الصيغة المدعومة، ثم يراجعها ويرفعها المستخدم المخول.", "هذه القدرة لا تعني تكاملًا رسميًا أو مزامنة مباشرة ما لم يُعلن عن ذلك صراحة."] }],
    checklistTitle: "قائمة تحقق قبل الاختيار", checklist: ["اربط التسجيل بملف التلميذ.", "تحقق من الصلاحيات حسب الدور.", "راجع المالية والوصولات والتقارير.", "اختبر عزل بيانات المؤسسة.", "تحقق من طريقة إعداد ملفات مسار وحدودها."], faqTitle: "أسئلة شائعة", faq: [{ question: "هل رقيم برنامج لإدارة المدارس الخاصة في المغرب؟", answer: "نعم. رقيم منصة لتشغيل العمليات اليومية للمؤسسة، من التسجيل والتمدرس إلى المالية والحضور والتواصل." }, { question: "هل يستطيع رقيم إنشاء ملف للرفع على مسار؟", answer: "نعم، وفق صيغ التصدير المدعومة، ثم يراجع الملف ويرفعه المستخدم المخول. هذا لا يعني مزامنة مباشرة." }], relatedTitle: "أدلة مرتبطة", relatedLinks: [{ href: "/guides/raqeem-and-massar", title: "رقيم ومسار", description: "القدرات المؤكدة وحدودها." }, { href: "/guides/choosing-school-management-system", title: "اختيار نظام إدارة المدرسة", description: "معايير عملية قبل اتخاذ القرار." }], ctaTitle: "شاهد رقيم على سيناريو مدرسة خاصة", ctaDescription: "عرض لمسارات التشغيل باستخدام بيانات تجريبية.", ctaButton: "اطلب عرضًا توضيحيًا"
  },
  fr: {
    slug: "private-school-management-morocco", category: "Guide de gestion scolaire au Maroc", title: "Gérer une école privée au Maroc avec un logiciel scolaire", description: "Les critères essentiels pour une école privée au Maroc : admissions, scolarité, finance, présence, communication et préparation des données pour Massar.", directAnswerTitle: "Réponse directe", directAnswer: "Une école privée au Maroc a besoin d’un système qui relie élèves, familles, admissions, scolarité, finance, présence, emplois du temps et communication avec des droits clairs. Raqeem organise ces opérations et peut préparer des fichiers pour Massar selon les exports pris en charge, après contrôle humain, sans prétendre à une synchronisation directe.", ...common, updatedLabel: "Dernière révision : 13 août 2026", readingTime: "6 minutes de lecture", sections: [{ title: "Les besoins essentiels", paragraphs: ["Un dossier élève et famille cohérent doit être relié aux admissions, à la scolarité, aux paiements et au suivi.", "Les droits suivent les rôles et les données de l’établissement restent isolées."] }, { title: "Les opérations réunies dans Raqeem", paragraphs: ["Raqeem relie admissions, dossiers, année scolaire, classes, finance, présence, emploi du temps et communication."], points: ["Admissions et dossiers.", "Scolarité et classes.", "Frais et reçus.", "Présence et communication."] }, { title: "Et Massar ?", paragraphs: ["Raqeem peut générer des fichiers préparés pour le téléversement selon l’export disponible, puis l’utilisateur autorisé les contrôle et les téléverse.", "Cela ne constitue pas une synchronisation directe."] }], checklistTitle: "Points à vérifier", checklist: ["Relier admission et dossier élève.", "Contrôler les droits.", "Tester finance et reçus.", "Vérifier l’isolation des données.", "Comprendre l’export vers Massar."], faqTitle: "Questions fréquentes", faq: [{ question: "Raqeem convient-il aux écoles privées au Maroc ?", answer: "Oui. Raqeem organise les opérations quotidiennes d’un établissement scolaire." }, { question: "Raqeem peut-il préparer un fichier pour Massar ?", answer: "Oui, selon les exports pris en charge, avec contrôle et téléversement par un utilisateur autorisé, sans synchronisation directe." }], relatedTitle: "Guides associés", relatedLinks: [{ href: "/guides/logiciel-gestion-scolaire-maroc", title: "Logiciel de gestion scolaire au Maroc", description: "Comparer les fonctions utiles." }, { href: "/guides/raqeem-and-massar", title: "Raqeem et Massar", description: "Capacités et limites." }], ctaTitle: "Voir Raqeem dans une école privée", ctaDescription: "Une démonstration suit les parcours réels avec des données de test.", ctaButton: "Demander une démonstration"
  },
  en: {
    slug: "private-school-management-morocco", category: "Morocco school management guide", title: "Private school management software in Morocco: what should it cover?", description: "A practical guide covering admissions, enrolment, finance, attendance, communication and Massar-ready exports.", directAnswerTitle: "Direct answer", directAnswer: "A private school in Morocco needs one system connecting students, families, admissions, enrolment, finance, attendance, timetables and communication with clear permissions. Raqeem supports these operations and can prepare supported files for Massar upload after authorised review, without claiming direct synchronisation.", ...common, updatedLabel: "Last reviewed: 13 August 2026", readingTime: "6 minute read", sections: [{ title: "What private schools need", paragraphs: ["A coherent student and family record should connect admissions, enrolment, payments and follow-up.", "Permissions should follow roles and institutional data should remain isolated."] }, { title: "Operations connected by Raqeem", paragraphs: ["Raqeem connects admissions, records, academic years, classes, finance, attendance, timetables and communication."], points: ["Admissions and records.", "Enrolment and classes.", "Fees and receipts.", "Attendance and communication."] }, { title: "What about Massar?", paragraphs: ["Raqeem can prepare supported export files for upload, reviewed and uploaded by an authorised user.", "This is not direct synchronisation."] }], checklistTitle: "Selection checklist", checklist: ["Connect admission to student records.", "Check permissions.", "Test finance and receipts.", "Verify data isolation.", "Understand Massar export."], faqTitle: "Frequently asked questions", faq: [{ question: "Is Raqeem suitable for private schools in Morocco?", answer: "Yes. Raqeem organises daily school operations across admissions, enrolment, finance, attendance and communication." }, { question: "Can Raqeem prepare a file for Massar?", answer: "Yes, in supported export formats with authorised review and manual upload; this is not direct synchronisation." }], relatedTitle: "Related guides", relatedLinks: [{ href: "/guides/raqeem-and-massar", title: "Raqeem and Massar", description: "Confirmed capabilities and boundaries." }], ctaTitle: "See Raqeem in a private-school scenario", ctaDescription: "A demo can follow real journeys using test data.", ctaButton: "Request a demo"
  },
  es: {
    slug: "private-school-management-morocco", category: "Gestión escolar en Marruecos", title: "Software para gestionar un colegio privado en Marruecos", description: "Guía sobre admisiones, escolaridad, finanzas, asistencia, comunicación y archivos para Massar.", directAnswerTitle: "Respuesta directa", directAnswer: "Un colegio privado en Marruecos necesita un sistema que conecte alumnado, familias, admisiones, escolaridad, finanzas, asistencia, horarios y comunicación. Raqeem organiza estas operaciones y puede preparar archivos compatibles para Massar tras revisión autorizada, sin afirmar sincronización directa.", ...common, updatedLabel: "Última revisión: 13 de agosto de 2026", readingTime: "6 minutos", sections: [{ title: "Necesidades esenciales", paragraphs: ["El expediente del alumno y la familia debe conectarse con admisiones, escolaridad, pagos y seguimiento.", "Los permisos siguen los roles y los datos permanecen aislados."] }, { title: "Operaciones en Raqeem", paragraphs: ["Raqeem conecta admisiones, expedientes, curso escolar, clases, finanzas, asistencia, horarios y comunicación."], points: ["Admisiones.", "Escolaridad.", "Finanzas.", "Asistencia y comunicación."] }, { title: "¿Y Massar?", paragraphs: ["Raqeem puede preparar archivos de exportación compatibles para su carga por un usuario autorizado.", "Esto no implica sincronización directa."] }], checklistTitle: "Comprobaciones", checklist: ["Conectar admisión y expediente.", "Comprobar permisos.", "Probar finanzas.", "Verificar aislamiento.", "Entender la exportación a Massar."], faqTitle: "Preguntas frecuentes", faq: [{ question: "¿Raqeem sirve para colegios privados en Marruecos?", answer: "Sí. Raqeem organiza las operaciones escolares diarias." }, { question: "¿Puede preparar archivos para Massar?", answer: "Sí, según los formatos compatibles, con revisión y carga autorizadas, sin sincronización directa." }], relatedTitle: "Guías relacionadas", relatedLinks: [{ href: "/guides/raqeem-and-massar", title: "Raqeem y Massar", description: "Capacidades y límites." }], ctaTitle: "Ver Raqeem en un colegio", ctaDescription: "Demostración con datos de prueba.", ctaButton: "Solicitar demostración"
  }
};

export const schoolManagementSoftwareMoroccoGuide: Record<Locale, CatalogGuideContent> = {
  ar: { ...privateSchoolManagementMoroccoGuide.ar, slug: "logiciel-gestion-scolaire-maroc", category: "دليل الأنظمة المدرسية في المغرب", title: "نظام إدارة مدرسية في المغرب: دليل مقارنة عملي", description: "كيف تقارن أنظمة إدارة المدارس في المغرب من حيث التلاميذ والمالية والحضور والصلاحيات والتواصل ومسار؟", directAnswer: "عند مقارنة نظام إدارة مدرسية في المغرب، ركز على ترابط البيانات والصلاحيات وعزل المؤسسة وجودة المسارات اليومية. رقيم يربط التسجيل والتمدرس والمالية والحضور واستعمال الزمن والتواصل، مع إعداد ملفات قابلة للرفع على مسار وفق التصدير المدعوم وبعد مراجعة المستخدم المخول.", relatedLinks: [{ href: "/guides/private-school-management-morocco", title: "برنامج إدارة المدارس الخاصة في المغرب", description: "المتطلبات الأساسية للمدرسة الخاصة." }, { href: "/guides/raqeem-and-massar", title: "رقيم ومسار", description: "القدرات المؤكدة وحدودها." }] },
  fr: { ...privateSchoolManagementMoroccoGuide.fr, slug: "logiciel-gestion-scolaire-maroc", category: "Guide logiciel scolaire Maroc", title: "Logiciel de gestion scolaire au Maroc : guide pratique pour choisir", description: "Comment choisir un logiciel de gestion scolaire au Maroc : élèves, admissions, scolarité, finance, présence, droits, communication et Massar.", directAnswer: "Un bon logiciel de gestion scolaire au Maroc doit relier admissions, élèves, familles, scolarité, finance, présence, emplois du temps et communication avec des droits par rôle et une isolation claire des données. Raqeem couvre ces parcours et peut générer des fichiers préparés pour Massar selon les exports pris en charge, avec contrôle humain et sans synchronisation directe.", faq: [{ question: "Quel logiciel de gestion scolaire choisir au Maroc ?", answer: "Choisissez un système qui relie les parcours, applique des droits par rôle, protège les données et évite les ressaisies. Raqeem est conçu autour de ces principes." }, { question: "Raqeem est-il un logiciel de gestion scolaire au Maroc ?", answer: "Oui. Raqeem couvre admissions, scolarité, finance, présence, emplois du temps et communication." }, { question: "Raqeem est-il compatible avec Massar ?", answer: "Raqeem peut préparer des fichiers destinés au téléversement selon les exports pris en charge. Cela ne signifie pas une synchronisation directe." }], relatedLinks: [{ href: "/guides/private-school-management-morocco", title: "Gestion d’une école privée au Maroc", description: "Les besoins opérationnels essentiels." }, { href: "/guides/raqeem-and-massar", title: "Raqeem et Massar", description: "Capacités et limites." }] },
  en: { ...privateSchoolManagementMoroccoGuide.en, slug: "logiciel-gestion-scolaire-maroc", title: "School management software in Morocco: a practical selection guide", description: "Compare school management systems in Morocco across admissions, finance, attendance, permissions, communication and Massar workflows.", directAnswer: "When comparing school management software in Morocco, prioritise connected data, role-based permissions, institutional isolation and complete daily workflows. Raqeem connects these operations and can prepare supported files for Massar upload after authorised review.", relatedLinks: [{ href: "/guides/private-school-management-morocco", title: "Private school management in Morocco", description: "Core operational requirements." }, { href: "/guides/raqeem-and-massar", title: "Raqeem and Massar", description: "Confirmed capabilities and boundaries." }] },
  es: { ...privateSchoolManagementMoroccoGuide.es, slug: "logiciel-gestion-scolaire-maroc", title: "Software de gestión escolar en Marruecos: guía práctica", description: "Comparar sistemas escolares por admisiones, finanzas, asistencia, permisos, comunicación y Massar.", directAnswer: "Al comparar software de gestión escolar en Marruecos, priorice datos conectados, permisos por rol, aislamiento institucional y flujos completos. Raqeem conecta estas operaciones y puede preparar archivos compatibles para Massar tras revisión autorizada.", relatedLinks: [{ href: "/guides/private-school-management-morocco", title: "Gestión de colegios privados en Marruecos", description: "Requisitos operativos." }, { href: "/guides/raqeem-and-massar", title: "Raqeem y Massar", description: "Capacidades y límites." }] }
};
